### ISSUE TITLE
5.5.3 - Breaking point in compilation

### ISSUE THREAD

**Issue by warnerbryce** [ONLYOFFICE/build_tools#103]
Hello to the devs and the community. 

It is impossible to compile OnlyOffice Document Server 5.5.3 with the last build_tools version. 
Still on a fresh Ubuntu 14.04 VM.
Using : python3 automate.py or python3 make.py gave this error on the same point 
```
Project MESSAGE: linux-64
Project MESSAGE: linux_64/release
make[1]: Entering directory `/home/nems/core/Common/DocxFormat/DocxFormatLib'
g++ -c -pipe -Wall -Wno-ignored-qualifiers -O2 -fPIC -std=gnu++11 -Wall -W -D_REENTRANT -DINTVER=5.5.3.0 -DLINUX -D_LINUX -DCRYPTOPP_DISABLE_ASM -DUNICODE -D_UNICODE -DDONT_WRITE_EMBEDDED_FONTS -DQT_NO_DEBUG -I. -I../../3dParty/boost/build/linux_64/include -I../../../../build_tools/tools/linux/qt_build/Qt-5.9.9/gcc_64/mkspecs/linux-g++ -o core_build/linux_64/release/obj/docxformatlib_logic.o docxformatlib_logic.cpp
In file included from ../../3dParty/boost/build/linux_64/include/boost/numeric/conversion/numeric_cast_traits.hpp:28:0,
                 from ../../3dParty/boost/build/linux_64/include/boost/numeric/conversion/cast.hpp:34,
                 from ../../3dParty/boost/build/linux_64/include/boost/lexical_cast/detail/converter_numeric.hpp:36,
                 from ../../3dParty/boost/build/linux_64/include/boost/lexical_cast/try_lexical_convert.hpp:33,
                 from ../../3dParty/boost/build/linux_64/include/boost/lexical_cast.hpp:32,
                 from ../Source/Common/../XML/Utils.h:46,
                 from ../Source/Common/SimpleTypes_Base.h:38,
                 from ../Source/Common/SimpleTypes_Word.h:34,
                 from ../Source/Common/SimpleTypes_Word.cpp:32,
                 from common_formatlib.cpp:40,
                 from docxformatlib_logic.cpp:32:
../../3dParty/boost/build/linux_64/include/boost/numeric/conversion/detail/numeric_cast_traits.hpp:12:91: fatal error: boost/numeric/conversion/detail/preprocessed/numeric_cast_traits_common.hpp: No such file or directory
     #include <boost/numeric/conversion/detail/preprocessed/numeric_cast_traits_common.hpp>
                                                                                           ^
compilation terminated.
make[1]: *** [core_build/linux_64/release/obj/docxformatlib_logic.o] Error 1
make[1]: Leaving directory `/home/nems/core/Common/DocxFormat/DocxFormatLib'
make: *** [sub--home-nems-core-Common-DocxFormat-DocxFormatLib-DocxFormatLib-pro-make_first-ordered] Error 2
Error (make): 2

```

Do you have clues for this problem ? 
Does Build_tools rely on Ubuntu 18.04 or 20.04 to compile now ? 
the .travis.yml get modified to specify NodeJS 12 but the automate.py still install 10.X, can this be the trick ?
Thank you

**Comment by ShockwaveNN** [comment]
> Do you have clues for this problem ?

That is gcc version?

> Does Build_tools rely on Ubuntu 18.04 or 20.04 to compile now ?
No, we change readme when we'll support newer versions

> the .travis.yml get modified to specify NodeJS 12 but the automate.py still install 10.X, can this be the trick ?

In travis config we only check markdown syntax, we do not use travis to build our project, since it's take a lot of time, and this out of travis limits

**Comment by warnerbryce** [comment]
It's GCC 4.8.4, this VM compiled with succes th 5.5.1 version

**Comment by ShockwaveNN** [comment]
Maybe there some leftovers from previous compilation?
Try to clean repo with `git clean -fdx`
If not help - could you provide Dockerfile with this error, so I could debug it on my side.
But default Dockerfile in this project should work fine with 5.5.3 (current master), I checked it several days ago

**Comment by warnerbryce** [comment]
i made a new folder to start from scratch nothing better... 
I can't use the dockerfile because i can't hold/stop the compile process i use some modified files from the github source.

**Comment by ShockwaveNN** [comment]
Until I will able to reproduce your problem - I cannot help your
So you saying 
> i use some modified files from the github source to have OnlyOffice like i want.

But also 
> The compilation process bug without having file modded

If you have problem with compilation of files unmodded - you can try to run unmodded Dockerfile and compare result and see how your system differs from Dockerfile

**Comment by warnerbryce** [comment]
Finally the compilation worked, i didn't delete the source from the ../build-tools folder. 
Sorry for disturbing.

**Comment by aportetecnologia** [comment]
warnerbryce you could you please give me information on how you compile or OO without limit of 20 connections. I'm having difficulties in the process.
