### ISSUE TITLE
404 when accessing AllFonts.js

### ISSUE THREAD

**Issue by mlunnon** [ONLYOFFICE/build_tools#106]
Hi, I have compiled only office and installed it in an Ubuntu 14.04 environment. However, when I come to use it I get an error in the Javascript console:
VM8 require.js:7 GET https://leaf.extinctionrebellion.uk/sdkjs/common/AllFonts.js net::ERR_ABORTED 404 (Not Found)
Uncaught Error: Script error for: allfonts
http://requirejs.org/docs/errors.html#scripterror
    at makeError (VM8 require.js:7)
    at HTMLScriptElement.onScriptError (VM8 require.js:7)
This happens when I try and view or edit a document. I have installed the sample php application to test this and also got a colleague to test it from a NextCloud platform. Both give the same error.
Thanks for any help.
Matthew

**Comment by ShockwaveNN** [comment]
Seems that AllFonts.js was not generated

What was output of https://github.com/ONLYOFFICE/build_tools#generate-fonts-data?

**Comment by mlunnon** [comment]
I'm not sure what the output was but looking back in the history I failed to rtfm and surprisingly if you type in random rubbish instead of following the instructions things don't work. Thanks for your help and sorry to waste your time!

**Comment by ShockwaveNN** [comment]
In that case I'll close issue, but feel free to comment or create new issue if something happen

**Comment by mlunnon** [comment]
I have now got some other errors when i try to edit a document, should I start a new issue or comment here?

**Comment by ShockwaveNN** [comment]
Yeah, better new one

**Comment by mlunnon** [comment]
OK thanks Pavel.
