### ISSUE TITLE
Document creation/edit error

### ISSUE THREAD

**Issue by mlunnon** [ONLYOFFICE/build_tools#107]
Hi,
I have compiled Only Office on an Ubuntu 14.04 server a few weeks ago. I am now testing it with a demo application. When I try and create a new document (or edit one) I get the following errors in the browser. 

	The document could not be saved ...

Followed by:

	Downlod failed ...

There are errors in both the converter and the docserver consoles on the onlyoffice server:

docserver
=========
```
[2020-06-17T08:58:01.294] [WARN] nodeJS - sqlQuery error sqlCommand: INSERT INTO task_result (id, status, status_info, :
error: syntax error at or near "ON"
    at Connection.parseE (/snapshot/server/build/server/DocService/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/snapshot/server/build/server/DocService/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/snapshot/server/build/server/DocService/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
converter
=========
```
[2020-06-17T08:58:01.398] [ERROR] nodeJS - error downloadFile:url=http://localhost/__1/new%20%284%29.docx;attempt=1;code:null;connect:null;(id=1913341311)
Error: Error response: statusCode:404 ;body:
```
It is a few weeks ago that I did the compile so is it possible that this is a version problem and I need to recompile?

Thanks for any help

**Comment by ShockwaveNN** [comment]
> sqlQuery error sqlCommand: INSERT INTO task_result (id, status, status_info, :
error: syntax error at or near "ON"

We got [several reports](https://github.com/ONLYOFFICE/DocumentServer/search?q=INSERT+INTO+task_result&type=Issues) of same error with our deb packed, so I think this is main reason, but never found out why this error happens

Whis DB are you using? 
Is it correctly initialized by https://github.com/ONLYOFFICE/build_tools#installing-and-configuring-postgresql all  thos steps?

**Comment by mlunnon** [comment]
I'm using postgres, I'll check the initialisation now.

**Comment by mlunnon** [comment]
Yes I've just looked back in the history and can see that I followed all the steps.

**Comment by ShockwaveNN** [comment]
You mention at other issue that you use some PHP based document management system, could you check that our docker of DocumentServer works fine with your PHP

Currenlty I'm not sure that to do with sql error, but I think 
> [2020-06-17T08:58:01.398] [ERROR] nodeJS - error downloadFile:url=http://localhost/__1/new%20%284%29.docx;attempt=1;code:null;connect:null;(id=1913341311)

is completly different error, and maybe your DMS send incorrect info

**Comment by mlunnon** [comment]
Sample app is from https://api.onlyoffice.com/editors/example/nodejs. I don't have docker at the moment but I can look into that. Meanwhile I have found the sql that is being run in the error log:
INSERT INTO task_result (id, status, status_info, last_open_date, user_index, change_id, callback, baseurl) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT (id) DO UPDATE SET last_open_date = $9, callback = task_result.callback || '{"userIndex":'  || (task_result.user_index + 1)::text || ',"callback":' || $10::text || '}', user_index = task_result.user_index + 1 RETURNING user_index as userindex;
When I run this in a console it also errors ERROR:  syntax error at or near "ON". Could this be a postgres version issue?

**Comment by ShockwaveNN** [comment]
> Could this be a postgres version issue?

May be, that version are you using

> Sample app is from https://api.onlyoffice.com/editors/example/nodejs

Yeah, this is good, it's our most advanced example, so I think it should work

**Comment by mlunnon** [comment]
psql (PostgreSQL) 9.3.24

**Comment by mlunnon** [comment]
I think that is it, ON CONFLICT didn't come in until 9.5 according to the postgres documentation.

**Comment by ShockwaveNN** [comment]
Oh, sorry I remember.
This error is correct, if it fails - we just use another method, so postgresql 9.3 should work

So just ignore it.

Back to 

> [2020-06-17T08:58:01.398] [ERROR] nodeJS - error downloadFile:url=http://localhost/__1/new%20%284%29.docx;attempt=1;code:null;connect:null;(id=1913341311)

Seems this is real error
Could you check that firewall (ufw) is disabled and if so - could you record a video that happened when you open file using nodejs example

**Comment by mlunnon** [comment]
Which firewall do you mean? the windows firewall? 
Do you mean a video of the web browser or the only office console?

**Comment by ShockwaveNN** [comment]
No, firewall on server, ufw on Ubuntu

Yes, video from client side in browser

**Comment by mlunnon** [comment]
ufw is inactive. Just trying to sort out a video

I have an swf video, can't upload it though.

**Comment by ShockwaveNN** [comment]
@mlunnon you can archive it in zip and attach

**Comment by ShockwaveNN** [comment]
Or, sorry don't meant to close issue

**Comment by mlunnon** [comment]
[OnlyOfficeDocumentEdit.zip](https://github.com/ONLYOFFICE/build_tools/files/4792230/OnlyOfficeDocumentEdit.zip)
[OnlyOfficeDocumentEdit.zip](https://github.com/ONLYOFFICE/build_tools/files/4792231/OnlyOfficeDocumentEdit.zip)

**Comment by ShockwaveNN** [comment]
Try to replace localhost in browser with your local ip, this may be a problem

Also you said you use nodejs example,
>Sample app is from https://api.onlyoffice.com/editors/example/nodejs.

 but in video there is php errors
I cannot guaranteed that php example is 100% working

**Comment by mlunnon** [comment]
OK so we have tested with a NextCloud installation and all seem to be working. Thanks for your help on this.

**Comment by ShockwaveNN** [comment]
@mlunnon In that case I'll close this issue
