### ISSUE TITLE
create debian or rpm package from compiled sources.

### ISSUE THREAD

**Issue by jrjena136** [ONLYOFFICE/build_tools#134]
@ShockwaveNN just wanted to have your attention if you could help.

As per the readme given in this repo, I followed the docker container approach to compile the `onlyoffice-documentserver` from sources. Somehow I managed to finish the compilation and it took around 3 hrs and all the generated output are being copied to the `out` directory. As I see there is a repo `onlyoffice/docker-documentserver` which is responsible to create the docker image and the `Dockerfile` uses the `apt-get install -yq onlyoffice-documentserver` command to install the document server.

I just want to know how we can build this debian package after the compilation is complete or is there any other ways which I should follow to create the package.

**Comment by ShockwaveNN** [comment]
As I answered here https://github.com/ONLYOFFICE/DocumentServer/issues/377#issuecomment-684837293

We do not provide an instruction how to build packages.
As far as I aware - in general - OpenSource products do not provide OS specific package build instruction, it's done by developers of each Linux distribution

**Comment by jrjena136** [comment]
@ShockwaveNN 
When I am seeing the docker container of the `onlyoffice-documentserver` i find below directory structure
```
ls -la /var/www/onlyoffice/documentserver
total 104
drwxr-xr-x  1 ds   ds    4096 Aug 13 00:45 .
drwxr-xr-x  1 root root  4096 Aug 13 00:45 ..
-rw-r--r--  1 ds   ds    5315 Aug 13 00:26 3rd-Party.txt
drwxr-xr-x 40 ds   ds    4096 Aug 13 00:44 core-fonts
drwxr-xr-x  1 ds   ds   12288 Aug 25 07:45 fonts
drwxr-xr-x  2 ds   ds    4096 Aug 13 00:44 license
-rw-r--r--  1 ds   ds   18241 Aug 13 00:26 LICENSE.txt
drwxr-xr-x  2 ds   ds    4096 Aug 13 00:44 npm
drwxr-xr-x  1 ds   ds    4096 Aug 13 00:44 sdkjs
drwxr-xr-x  1 ds   ds    4096 Aug 25 07:45 sdkjs-plugins
drwxr-xr-x  1 ds   ds    4096 Aug 13 00:43 server
drwxr-xr-x  1 ds   ds    4096 Aug 13 00:44 web-apps
```
but following output i am getting when i am compiling from sources.
```
ls build_tools/out/linux_64/onlyoffice/documentserver
total 28
drwxr-xr-x  7 root root 4096 Aug 28 10:14 .
drwxr-xr-x  7 root root 4096 Aug 28 10:14 ..
drwxr-xr-x 40 root root 4096 Aug 28 10:14 core-fonts
drwxr-xr-x  6 root root 4096 Aug 28 10:07 sdkjs
drwxr-xr-x 12 root root 4096 Aug 28 10:14 sdkjs-plugins
drwxr-xr-x 12 root root 4096 Aug 28 10:17 server
drwxr-xr-x  4 root root 4096 Aug 28 10:01 web-apps

ls build_tools/out/linux_64/onlyoffice/documentserver-example
total 51536
drwxr-xr-x 3 root root     4096 Aug 28 10:14 .
drwxr-xr-x 7 root root     4096 Aug 28 10:14 ..
drwxr-xr-x 2 root root     4096 Aug 28 08:24 config
-rwxr-xr-x 1 root root 52752470 Aug 28 10:14 example
```

- I am trying understand what are the use of those missing files after compilation.
- If I create the package without those missing files will there be any problem running the document server.
- If yes, from where i can get these missing files.

needs your output on this.

Thanks

**Comment by ShockwaveNN** [comment]
> I am trying understand what are the use of those missing files after compilation.

There is no crucial files are missed. Some files are generated on runtime, some file are for Docker configuration

> If I create the package without those missing files will there be any problem running the document server.

I don't think so

> If yes, from where i can get these missing files.

I think you can extract them from Docker image, but not sure which file you'll need, probably not a single one

**Comment by jrjena136** [comment]
This `npm, fonts and license` directory are these generated at run time? if we don't include those while creating package, will there be any problem.

**Comment by ShockwaveNN** [comment]
`npm` is for configure reason and contains `json` command to change configs
`fonts` are generated on this step https://github.com/ONLYOFFICE/build_tools#generate-fonts-data (may have other location though)
`license` is not needed to work

**Comment by jrjena136** [comment]
i created a tar from the compiled output directory and extracted inside the container under `/var/www/onlyoffice`. in the entrypoint it is looking for `npm` and getting this in log
```chown: invalid user: ‘ds:ds’
chown: invalid user: ‘ds:ds’
chown: invalid user: ‘ds:ds’
/app/ds/run-document-server.sh: line 87: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
/app/ds/run-document-server.sh: line 96: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
/app/ds/run-document-server.sh: line 103: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
/app/ds/run-document-server.sh: line 104: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
/app/ds/run-document-server.sh: line 105: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
/app/ds/run-document-server.sh: line 106: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
/app/ds/run-document-server.sh: line 108: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
/app/ds/run-document-server.sh: line 160: -3: substring expression < 0
```

**Comment by ShockwaveNN** [comment]
You shouldn't place this in production Docker, there is a lot of additional configuration changes, this will not work

You can try to use mine test docker from [here](https://github.com/onlyoffice-testing-robot/onlyoffice-documentserver-run-compiled) but this is just an example, if you want production ready product - you should use our official Docker image

**Comment by jrjena136** [comment]
I think the `Docker-Documentserver` repo creates your official docker image. What needs to be done if I want to use my compiled output and include those to create the docker image.

**Comment by ShockwaveNN** [comment]
> I think the Docker-Documentserver repo creates your official docker image

Yes, it does, but it's designed for using builded `.deb` file, not from raw output from source compilation

So your option or do it yourself, or use Docker provided by me

**Comment by jrjena136** [comment]
<img width="1625" alt="Screen Shot 2020-09-02 at 3 55 21 PM" src="https://user-images.githubusercontent.com/14884739/91971709-42ec7b80-ed37-11ea-80ef-8cf06aa1d1b7.png">


What is the meaning of this. I just replaced the `docservice` file inside container and it is giving me like this

**Comment by ShockwaveNN** [comment]
> I just replaced the docservice file inside container and it is giving me like this

You can't do it, it's incorrect, you can just replace files in production Docker with compalied version, I said this several times

You could copy some files from production docker in your compiled version, but not the other way for any files (some may be work, but `docservice` is crucial part and will not work, since compiled version has 0.0.0.0 as app version)

**Comment by jrjena136** [comment]
so finally I followed this https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx to setup from compiled sources. its now up and running. how can I access editor?

**Comment by ShockwaveNN** [comment]
DocumentServer should be aviable on 80 port, but please note that it's not contains any Document Management System, you should use one of [integration example](https://github.com/ONLYOFFICE/document-server-integration) or connect to nextcloud/owncloud etc

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
