### ISSUE TITLE
How to compile test Document Server from source?

### ISSUE THREAD

**Issue by kaners80** [ONLYOFFICE/build_tools#188]
I know it is possible to run test Document Server builds from Docker, for example onlyoffice / 4testing-documentserver: latest.
But how to get the version of "test Document Server" using build_tools?

**Comment by ShockwaveNN** [comment]
Hi, If you checkout build_tools repo for example from `release/v6.1.0` and run default build process you got DocumentServer v6.1.0

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
