### ISSUE TITLE
compile error on ubuntu20

### ISSUE THREAD

**Issue by xyz0101** [ONLYOFFICE/build_tools#251]
**my system is ubuntu20 , the error occured when I run automate.py** 

**this is  the error:**

Running "closure-compiler:js" (closure-compiler) task
Warning: Compilation error Use --force to continue.

Aborted due to warnings.

**I found it happend on Running "build-sdk" task ，and I execute** 

`cd sdkjs && make `

**but it aslo has error :**

    Running "closure-compiler:js" (closure-compiler) task
    Verifying property closure-compiler.js exists in config...OK
    File: [no files]
    Options: args=["--externs=../common/externs/global.js","--externs=../common/externs/jquery-3.2.js","--externs=../common/externs/xregexp-3.0.0.js","--externs=../common/externs/sockjs.js","--externs=../common/externs/jszip.min.js","--externs=../common/externs/jszip-utils.js","--externs=../common/externs/word.js","--externs=../common/externs/cell.js","--externs=../common/externs/slide.js","--rewrite_polyfills=true","--jscomp_off=checkVars","--warning_level=QUIET","--compilation_level=ADVANCED","--module=polyfill:1:","--js=empty.js","--module=fontswasm:1:polyfill","--js=fonts-wasm-tmp.js","--module=fontsjs:1:fontswasm","--js=fonts-js-tmp.js","--module=word:1:fontswasm","--js=sdk-word-tmp.js","--module=cell:1:fontswasm","--js=sdk-cell-tmp.js","--module=slide:1:fontswasm","--js=sdk-slide-tmp.js"]
    Warning: Compilation error Use --force to continue.
    
    Aborted due to warnings.
    make: *** [Makefile:51：word/sdk-all.js] error 6

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
