### ISSUE TITLE
compile error on ubuntu 14.04

### ISSUE THREAD

**Issue by git-vhu** [ONLYOFFICE/build_tools#252]
Hi,
I get this error on Ubuntu 14.04

/usr/bin/ld: uvectr32.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [../lib/libicuuc.so.58.2] Error 1
make[1]: Leaving directory `/home/xxxxxxx/build-tool/core/Common/3dParty/icu/icu/source/common'
make: *** [install-recursive] Error 2
Error (make): 2
Error (./make.py): 1

**Comment by ShockwaveNN** [comment]
Hi, could you provide step by step what did you do and better - Dockerfile with this error to reproduce

**Comment by git-vhu** [comment]
sudo apt update
mkdir build-tool
cd build-tool/
sudo apt-get install -y python git
git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/tools/linux
./automate.py server

**Comment by ShockwaveNN** [comment]
@git-vhu Could you run compilations of all products and see if error differs?

```
cd tools/linux && \
    python3 ./automate.py
```

Like in [this Dockerfile](https://github.com/ONLYOFFICE/build_tools/blob/master/Dockerfile)

**Comment by git-vhu** [comment]
Yes same error :

`/usr/bin/install -c -m 644 ./unicode/uversion.h /home/xxxxx/build-tool/build_tools/scripts/../../core/Common/3dParty/icu/linux_64/usr/local/include/unicode
g++ -O3  -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long --std=c++0x      -shared -Wl,-Bsymbolic -Wl,-soname -Wl,libicuuc.so.58 -o ../lib/libicuuc.so.58.2 errorcode.o putil.o umath.o utypes.o uinvchar.o umutex.o ucln_cmn.o uinit.o uobject.o cmemory.o charstr.o cstr.o udata.o ucmndata.o udatamem.o umapfile.o udataswp.o ucol_swp.o utrace.o uhash.o uhash_us.o uenum.o ustrenum.o uvector.o ustack.o uvectr32.o uvectr64.o ucnv.o ucnv_bld.o ucnv_cnv.o ucnv_io.o ucnv_cb.o ucnv_err.o ucnvlat1.o ucnv_u7.o ucnv_u8.o ucnv_u16.o ucnv_u32.o ucnvscsu.o ucnvbocu.o ucnv_ext.o ucnvmbcs.o ucnv2022.o ucnvhz.o ucnv_lmb.o ucnvisci.o ucnvdisp.o ucnv_set.o ucnv_ct.o resource.o uresbund.o ures_cnv.o uresdata.o resbund.o resbund_cnv.o ucurr.o messagepattern.o ucat.o locmap.o uloc.o locid.o locutil.o locavailable.o locdispnames.o locdspnm.o loclikely.o locresdata.o bytestream.o stringpiece.o stringtriebuilder.o bytestriebuilder.o bytestrie.o bytestrieiterator.o ucharstrie.o ucharstriebuilder.o ucharstrieiterator.o dictionarydata.o appendable.o ustr_cnv.o unistr_cnv.o unistr.o unistr_case.o unistr_props.o utf_impl.o ustring.o ustrcase.o ucasemap.o ucasemap_titlecase_brkiter.o cstring.o ustrfmt.o ustrtrns.o ustr_wcs.o utext.o unistr_case_locale.o ustrcase_locale.o unistr_titlecase_brkiter.o ustr_titlecase_brkiter.o normalizer2impl.o normalizer2.o filterednormalizer2.o normlzr.o unorm.o unormcmp.o loadednormalizer2impl.o chariter.o schriter.o uchriter.o uiter.o patternprops.o uchar.o uprops.o ucase.o propname.o ubidi_props.o ubidi.o ubidiwrt.o ubidiln.o ushape.o uscript.o uscript_props.o usc_impl.o unames.o utrie.o utrie2.o utrie2_builder.o bmpset.o unisetspan.o uset_props.o uniset_props.o uniset_closure.o uset.o uniset.o usetiter.o ruleiter.o caniter.o unifilt.o unifunct.o uarrsort.o brkiter.o ubrk.o brkeng.o dictbe.o filteredbrk.o rbbi.o rbbidata.o rbbinode.o rbbirb.o rbbiscan.o rbbisetb.o rbbistbl.o rbbitblb.o serv.o servnotf.o servls.o servlk.o servlkf.o servrbf.o servslkf.o uidna.o usprep.o uts46.o punycode.o util.o util_props.o parsepos.o locbased.o cwchar.o wintz.o dtintrv.o ucnvsel.o propsvec.o ulist.o uloc_tag.o icudataver.o icuplug.o listformatter.o ulistformatter.o sharedobject.o simpleformatter.o unifiedcache.o uloc_keytype.o ubiditransform.o pluralmap.o -L../lib -L../stubdata -licudata -lpthread -ldl -lm
/usr/bin/ld: uvectr32.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [../lib/libicuuc.so.58.2] Error 1
make[1]: Leaving directory `/home/xxxxxxxx/build-tool/core/Common/3dParty/icu/icu/source/common'
make: *** [install-recursive] Error 2
Error (make): 2
Error (./make.py): 1
`

**Comment by ShockwaveNN** [comment]
I justed check our default [Dockerfile](https://github.com/ONLYOFFICE/build_tools/blob/master/Dockerfile) from ground-up and seems there is no such error like yours

What `gcc` and `ld` are you using?
mine are:
![image](https://user-images.githubusercontent.com/668524/104434863-cdbe6c00-559c-11eb-90e3-72bc33fb2fe4.png)

**Comment by git-vhu** [comment]
Hi,
I move to 16.04 and with 
`cd tools/linux && \
    python3 ./automate.py
`
compile works !

Just little change I made to get source ICU 58.2 in "build_tools/scripts/core_common/modules/icu.py"
the repo you use does'nt works for version 58.2.

Tks for your help.

**Comment by ShockwaveNN** [comment]
> the repo you use does'nt works for version 58.2.

Yeah, we aware of this
But please note that we currently compiling our source code on 14.04 so there may be some other troubles, but I'll close this issue for now
