### ISSUE TITLE
Building server fails with "Cannot find file: .../videoplayerlib.pro"

### ISSUE THREAD

**Issue by drebs** [ONLYOFFICE/build_tools#253]
Hello, dear ONLYOFFICE devs!

I'm trying to build the latest version of ONLYOFFICE DocumentServer using this repo with the following `Dockerfile`:

```
FROM ubuntu:14.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y git python sudo
RUN git clone \
    --depth=1 \
    --recursive \
    --branch v6.2.0.45 \
    https://github.com/ONLYOFFICE/build_tools.git \
    /build_tools
RUN cd /build_tools/tools/linux && \
    ./automate.py --branch=tags/v6.2.0.45 server
```

And after a couple of hours I get the following error:

```
Cannot find file: /desktop-sdk/ChromiumBasedEditors/videoplayerlib/videoplayerlib.pro.
make: *** [sub--desktop-sdk-ChromiumBasedEditors-videoplayerlib-videoplayerlib-pro-make_first-ordered] Error 2
```

Here's a complete build log from slightly more complex Dockerfile (open with `less -r` because it's colored): [job.log.gz](https://github.com/ONLYOFFICE/build_tools/files/5804738/job.log.gz)

Am I doing something wrong?

Thanks!

**Comment by ShockwaveNN** [comment]
@drebs Hi, v6.2.0 is currently in development and not 100% finished, so it's better not to rely on some tag, but just build from `release/v6.2.0` branch if you really need WIP version

And also you could try to build all packages, not just a `server`, sometimes this helps

So could you try something like this:
```
FROM ubuntu:14.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y git python sudo
RUN git clone \
    --depth=1 \
    --recursive \
    --branch release/v6.2.0 \
    https://github.com/ONLYOFFICE/build_tools.git \
    /build_tools
RUN cd /build_tools/tools/linux && \
    ./automate.py
    ```

**Comment by drebs** [comment]
@ShockwaveNN, thanks a lot, my problem was indeed assuming that the latest (non `v99...`) release tag of `onlyffice/build_tools` corresponded to the latest released release version of `onlyoffice/DocumentServer`.

I now first fetch the latest release tag from `onlyoffice/DocumentServer` and then I search for the most recent `build_tools` tag starting with that prefix.

Thanks!

**Comment by ShockwaveNN** [comment]
Yeah, you got it right

We got pretty complecated release process, but only build that marked as `release` on github page, or docker tag version in `onlyoffice/documentserver` repo are really stable and fully tested

All other version (99.99 always will be not stable and 6.2.0 until we ready to release 6.2.0 may have compilation and\or any other problem)
