### ISSUE TITLE
Error while compiling with Docker (Spellchecker)

### ISSUE THREAD

**Issue by linuxrecon** [ONLYOFFICE/build_tools#265]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The compilation with Docker (as described in [build_tools](https://github.com/ONLYOFFICE/build_tools) fails with master branch and latest tag (v6.1.1, didn't checked earlier tags though). It seems like that building Spellchecker fails. See attached [output.txt](https://github.com/ONLYOFFICE/DocumentServer/files/6049925/output.txt) for more information.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
As described in the build_tools repo, checkout build_tools

`git clone https://github.com/ONLYOFFICE/build_tools`

and build the DocumentServer with the given command

`cd build_tools
mkdir out
docker build --tag onlyoffice-document-editors-builder .
docker run -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder`

**What is the expected behavior?**
Successful build with output of the binaries in the folder "out".

**Did this work in previous versions of DocumentServer?**
I can't say this for sure as this is the first time I'm trying to compile the DocumentServer on my own.

**DocumentServer version:**
6.1.1

**Operating System:**
Debian 10 with the latest docker.io Package installed (= Docker Version 18.09.1).

The Dockerfile comes from the build_tools repo and is unchanged, which means it uses the ubuntu:14.04 Image for building.

**Comment by ShockwaveNN** [comment]
Hi, we got same error recently and seems it's somehow related to npm v7
I see in your logs you're using npm v7 as well

We've downgraded to npm v6 like this https://github.com/ONLYOFFICE/build_tools/pull/264 and everything seems fine

**Comment by linuxrecon** [comment]
Thanks for your answer @ShockwaveNN 

Indeed this is the problem. Maybe you can add this to the Readme in the Docker section? Just for the records, I solved the issue in manually changing the following line (No. 58) in the tools/linux/automate.py file:

`base.cmd("sudo", ["npm", "install", "-g", "npm"])`

to

`base.cmd("sudo", ["npm", "install", "-g", "npm@6"])`

**Comment by ShockwaveNN** [comment]
@linuxrecon We already merged this to master several days ago, when we released v6.2.0

https://github.com/ONLYOFFICE/build_tools/blob/master/tools/linux/automate.py#L58
