### ISSUE TITLE
Not able to Compile ONLYOFFICE Docs for a local server

### ISSUE THREAD

**Issue by sreejan-chowdhury** [ONLYOFFICE/build_tools#290]
I am using the following link for Compiling ONLYOFFICE Docs for a local server : https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx?utm_source=blog&utm_medium=social&utm_campaign=build_tools&_ga=2.222489240.240936113.1618909307-600347315.1616501454

I am running it on Ubuntu 16.

If fails and gives me the following o/p : 

>                 
> ../../../DesktopEditor/fontengine/./application_generate_fonts_common.h:104:17: warning: ‘void NSCommon::makeLower(std::__cxx11::string&)’ defined but not used [-Wunused-function]
>      static void makeLower(std::string& url)
>                  ^
> ../../../DesktopEditor/fontengine/./application_generate_fonts_common.h:115:17: warning: ‘void NSCommon::makeLowerW(std::__cxx11::wstring&)’ defined but not used [-Wunused-function]
>      static void makeLowerW(std::wstring& url)
>                  ^
> ../../../DesktopEditor/fontengine/./application_generate_fonts_common.h:127:17: warning: ‘void NSCommon::WriteLog(const string&, const wstring&)’ defined but not used [-Wunused-function]
>      static void WriteLog(const std::string& sLogFile, const std::wstring& sData)
>                  ^
> ../../../DesktopEditor/fontengine/./application_generate_fonts_common.h:139:25: warning: ‘std::__cxx11::wstring NSCommon::GetFileExtention(const wstring&)’ defined but not used [-Wunused-function]
>      static std::wstring GetFileExtention(const std::wstring& sPath)
>                          ^
> ../../../DesktopEditor/fontengine/./application_generate_fonts_common.h:146:25: warning: ‘std::__cxx11::wstring NSCommon::GetFileName(const wstring&)’ defined but not used [-Wunused-function]
>      static std::wstring GetFileName(const std::wstring& sPath)
>                          ^
> ../../../DesktopEditor/fontengine/./application_generate_fonts_common.h:169:25: warning: ‘std::__cxx11::wstring NSCommon::GetDirectoryName(const wstring&)’ defined but not used [-Wunused-function]
>      static std::wstring GetDirectoryName(const std::wstring& sPath)
>                          ^
> g++ -Wl,-rpath,'$ORIGIN' -Wl,-rpath,'$ORIGIN/system' -Wl,--disable-new-dtags -Wl,-O1 -o ../../../build/bin/linux_64/standardtester core_build/linux_64/release/obj/OfficeFileFormatChecker2.o core_build/linux_64/release/obj/pole.o core_build/linux_64/release/obj/unicode_util.o core_build/linux_64/release/obj/main.o   /home/sreejan/Desktop/core/Common/3dParty/icu/linux_64/build/libicuuc.so.58 /home/sreejan/Desktop/core/Common/3dParty/icu/linux_64/build/libicudata.so.58 -L/home/sreejan/Desktop/core/Test/Applications/StandardTester/../../../../core/build/lib/linux_64 -lkernel -lgraphics -lUnicodeConverter 
> make[1]: Leaving directory '/home/sreejan/Desktop/core/Test/Applications/StandardTester'
> cd ../desktop-sdk/ChromiumBasedEditors/videoplayerlib/ && ( test -e /home/sreejan/Desktop/build_tools/../desktop-sdk/ChromiumBasedEditors/videoplayerlib/Makefile.videoplayerliblinux_64 || /home/sreejan/Desktop/build_tools/tools/linux/qt_build/Qt-5.9.9/gcc_64/bin/qmake -o /home/sreejan/Desktop/build_tools/../desktop-sdk/ChromiumBasedEditors/videoplayerlib/Makefile.videoplayerliblinux_64 /home/sreejan/Desktop/desktop-sdk/ChromiumBasedEditors/videoplayerlib/videoplayerlib.pro -nocache 'CONFIG+=server  ' ) && make -f /home/sreejan/Desktop/build_tools/../desktop-sdk/ChromiumBasedEditors/videoplayerlib/Makefile.videoplayerliblinux_64 
> Cannot find file: /home/sreejan/Desktop/desktop-sdk/ChromiumBasedEditors/videoplayerlib/videoplayerlib.pro.
> makefiles/build.makefile_linux_64:1321: recipe for target 'sub--home-sreejan-Desktop-desktop-sdk-ChromiumBasedEditors-videoplayerlib-videoplayerlib-pro-make_first-ordered' failed
> make: *** [sub--home-sreejan-Desktop-desktop-sdk-ChromiumBasedEditors-videoplayerlib-videoplayerlib-pro-make_first-ordered] Error 2
> Error (make): 2
> Error (./make.py): 1

**Comment by sreejan-chowdhury** [comment]
What I am trying to do is build Onlyoffice doc server. 
I can clone the repo and build from there. I can then deploy this on a server.
What are the steps if I want to build from the cloned repo and run docserver on a server?

**Comment by ShockwaveNN** [comment]
> I can clone the repo and build from there. I can then deploy this on a server.
> What are the steps if I want to build from the cloned repo and run docserver on a server?

I think I do not understand a question

Quest way is to build all products - using docker and [this guide](https://github.com/ONLYOFFICE/build_tools#using-docker)

**Comment by sreejan-chowdhury** [comment]
I will try it out in Ubuntu 14.
There are two things that I am trying to achieve:
1. Make changes to DocServer code to allow https connection ( not via nginx ).
2. Create a build from these changes and deploy the new build on  machine in a particular folder (not in etc/onlyoffice).

To accomplish these, what should I do?

**Comment by ShockwaveNN** [comment]
> To accomplish these, what should I do?

For a second task you should follow the [guide](https://github.com/ONLYOFFICE/build_tools#installing-and-configuring-document-server-dependencies) on running compiled DocumentServer 

For a first one I don't quite understand what are you planning to do, but it's up to you )

**Comment by sreejan-chowdhury** [comment]
For the first task : docservice currently runs on http. I want to make it run on https.

I have cloned the repo : https://github.com/ONLYOFFICE/DocumentServer on my machine. How do I specify this local repo in `automate.py`, so that the build is generated from the local? Is there any other way of doing it?

**Comment by ShockwaveNN** [comment]
I've moved this to GitHub Disussions, since currently there is no actual issue, but more a question
