### ISSUE TITLE
Enhancement: Make build_tools more functional 

### ISSUE THREAD

**Issue by h8ghbzc9bbr8c7** [ONLYOFFICE/build_tools#310]
Currently build_tools are only able to build master (as documented). Building a release branch (as currently the release/v6.3.0 branch) is not supported and fails. Master is behind the release branch and contains bugs which prevent building.

This prevents willing people to test features and report bugs early. If you are interested in such "third party support" I would like suggest to invest some work in the build_tools to allow an "easy build".

Thanks for listening!

**Comment by ShockwaveNN** [comment]
> Building a release branch (as currently the release/v6.3.0 branch) is not supported and fails. 

Huh? Why is that?

You should checkout `release/v6.3.0` branch of build_tools and build should finished, I've tried it like two days ago

**Comment by h8ghbzc9bbr8c7** [comment]
Thanks! I assumed that the build in a branch is not supposed to work because of the comment in the README.md. I will file a new issue regarding the build error.

**Comment by ShockwaveNN** [comment]
> I  assumed that the build in a branch is not supposed to work because of the comment in the README.md

No this statement means that we got very active development process and sometimes something may be broken, sometimes just some minor think but sometimes can be major trouble, but usually we fix it within a day-two
