### ISSUE TITLE
curl: (56) Recv failure

### ISSUE THREAD

**Issue by alfabeto2019** [ONLYOFFICE/build_tools#345]
when i tried to run python automate.py server,i got this error:
curl: (56) Recv failure
Error (curl): 56
Error (./make.py): 1
i'm sure that firewall is closed on Ubuntu.
can u give me some advices?

**Comment by ShockwaveNN** [comment]
> i'm sure that firewall is closed on Ubuntu.

In that case disable it (temporaly)

I think it failing on downloading some third party libs and we cannot do anything about it
