### ISSUE TITLE
Incorrect dictionaries location resulting broken Spell Check

### ISSUE THREAD

**Issue by ghuarng** [ONLYOFFICE/build_tools#354]
Built on Ubuntu 20.04 with:
`automate.py`

Tested on the same Node.js integration example.

---------------------------------------
OnlyOffice Docs functions as intended except for the SpellChecker (no highlighting/suggestions). The Docker image's (v6.3) SpellChecker is functional.

Replacing the build_tools build's "spellchecker" executable with the Docker image's "spellchecker" executable still results in a non-functional SpellChecker. 

However, replacing the Docker image's "spellchecker" executable with the build_tools build's "spellchecker" executable results in a functional SpellChecker, suggesting that the executable is probably not the cause of the issue.

[UPDATE]
New discovery -- SpellChecker works even if the "spellchecker" executable is deleted from the Docker image.

**Comment by ShockwaveNN** [comment]
Since release v6.3.0 we remove spellchecker as stand-alone service on backed and moved in Javascript Service Worker, inside browser

We got leftovers of spellchecker in build_tools, but they should be removed in next major release

> New discovery -- SpellChecker works even if the "spellchecker" executable is deleted from the Docker image.

Could you clarify, does spellchecker works with compiling from source for you in result?

**Comment by ghuarng** [comment]
No, spellchecker does not work when compiling from source.

Diffing the `/sdkjs/common/spell/spell` directory of the build_tools result and the Docker image shows that they are identical.

Just to clarify, is the build_tools result on v6.0.0?

**Comment by ShockwaveNN** [comment]
> Just to clarify, is the build_tools result on v6.0.0?

Not sure that I understand this question, but did you build using master branch of `build_tools` - in result should be same version as Docker Image v6.3.1

**Comment by ghuarng** [comment]
I cloned the repository using `git clone https://github.com/ONLYOFFICE/build_tools.git`

After building, every file that specifies the product version says it's on v6.0.0.

Should I specify the `master` branch when cloning?

**Comment by ShockwaveNN** [comment]
> specifies the product version says it's on v6.0.0.

Ah got it, version is hard coded in https://github.com/ONLYOFFICE/build_tools/blob/master/version

I think we forgot to change it but it's not the source of your problem, checking spellchecker by myself right now

**Comment by ShockwaveNN** [comment]
Seems we found a problem

Could you check that by default you have dictonaries folder located in:
```
out/linux_64/onlyoffice/documentserver/server/SpellChecker/dictionaries
```

If so - please move it on several levels up to root of Documentserver:
```
sudo cp ./server/SpellChecker/dictionaries ./ -R
```

So root looks like this:
![image](https://user-images.githubusercontent.com/668524/126471007-79e1c126-1b88-4664-99db-cb2141b06e47.png)

**Comment by ShockwaveNN** [comment]
Dev team informing me that this issue is probably fixed on v6.4.0 (still unreleased) in https://github.com/ONLYOFFICE/build_tools/pull/337/files#diff-ce7d2c06b8cf23ff0d8e1b5987268330ee1ad69490dc633e3a6e3fc4704120daR138

Rechecking this now

**Comment by ShockwaveNN** [comment]
Rechecked this - still path not correct, missed for one level
Now dictonaries located at
`out/linux_64/onlyoffice/documentserver/server/dictionaries`

I've create issue 51440 in our private issue tracker to get attention of developers, but workaround with manual move should work fine

**Comment by ghuarng** [comment]
Hi Pavel,

By default, `dictionaries` is in `out/linux_64/onlyoffice/documentserver/server/SpellChecker/dictionaries`

I copied `dictionaries` to the root of DocumentServer and spellchecker is working. Thank you so much!

**Comment by ShockwaveNN** [comment]
This problem is fixed in https://github.com/ONLYOFFICE/build_tools/commit/c6cc482b921786330c31215d67b7b5b9057e0bfc

And should be release in v6.4.0

**Comment by ShockwaveNN** [comment]
V6.4.0 source code is released to master and problem should be fixed
