### ISSUE TITLE
connect refused when building 

### ISSUE THREAD

**Issue by alfabeto2019** [ONLYOFFICE/build_tools#357]
when i build source code recently,i found there was an error,it says connect refused 433,and locate the exception at this line download("https://onlyoffice.github.io/sdkjs-plugins/v1/plugins.js", out_dir + "/plugins.js"),i tried to navigate this url,and it was surely down.

**Comment by ShockwaveNN** [comment]
Hi, this is github url and it's fine for me right now

So, maybe github was down or blocked in your region in that time, I don't think we can do anything about this

P.S. Moved this issue to `build_tools` repo

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
