### ISSUE TITLE
Compiling stopped: Missing content in folder videoplayerlib

### ISSUE THREAD

**Issue by hnk73** [ONLYOFFICE/build_tools#363]
Hi,

running  "./automate.py server"  (from master branch) failed.

The following message was generated:

"Cannot find file: /home/axel/desktop-sdk/ChromiumBasedEditors/videoplayerlib/videoplayerlib.pro.
makefiles/build.makefile_linux_64:1321: recipe for target 'sub--home-axel-desktop-sdk-ChromiumBasedEditors-videoplayerlib-videoplayerlib-pro-make_first-ordered' failed
make: *** [sub--home-axel-desktop-sdk-ChromiumBasedEditors-videoplayerlib-videoplayerlib-pro-make_first-ordered] Error 2
Error (make): 2
Error (./make.py): 1"

And it´s right, the folder "/desktop-sdk/ChromiumBasedEditors/videoplayerlib"is empty!

How to fix?

**Comment by ShockwaveNN** [comment]
Hi, seems we got this problem but fixed it

> (from master branch) 

Coud you tell exact commit of `build_tools`

And there is workaround

You can run `./automate.py` instance of `./automate.py server` and there will be no error with `videoplayer`. Build time will increase, but like several minutes more, not significant

**Comment by hnk73** [comment]
indeed, now it´s working, thank´s!
I can´t tell you the exact commit, i tried out a few and can´t remember exactly.

Cheers,
Axel

**Comment by ShockwaveNN** [comment]
> I can´t tell you the exact commit, i tried out a few and can´t remember exactly.

```
git rev-parse HEAD
```

Is your friend

If compilation is working I'll close this issue, glad this helped
