### ISSUE TITLE
./tools/build/src/engine/build.sh: not found

### ISSUE THREAD

**Issue by HULIANGA** [ONLYOFFICE/build_tools#366]
run ./automate.py server

[fetch & build]: boost
./bootstrap.sh: 1: ./tools/build/src/engine/build.sh: not found
Building Boost.Build engine with toolset ... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
Error (./bootstrap.sh): 1
Error (./make.py): 1

**build_tools base repo version**: master

**Operating system**: Ubuntu 64 20.04.2.0

**Compiler version**:

**Comment by ShockwaveNN** [comment]
Hi, this error is new for me, seems for some reason not all subrepos of Boost are downloade

I'll try to reproduce this error
In mean time

> build_tools base repo version: master

Could you specify exact git version of repo, to be sure?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by RehArk** [comment]
Solution here :
https://github.com/ONLYOFFICE/build_tools/issues/461
