### ISSUE TITLE
Compiling stopped with error: 'module' object has no attribute 'make'

### ISSUE THREAD

**Issue by hnk73** [ONLYOFFICE/build_tools#367]
The attempt of compiling with "./automate.py" stopped with the following error:

delete warning [file not exist]: ./cef_binary.7z.data
Traceback (most recent call last):
  File "./make.py", line 70, in <module>
    make_common.make()
  File "scripts/core_common/make_common.py", line 21, in make
    icu.make()
AttributeError: 'module' object has no attribute 'make'
Error (./make.py): 1

Any ideas?

**Comment by ShockwaveNN** [comment]
I think it's network error and cef_binary.7z do not downloaded correctly

It's url something like this:
https://d2ettrnqo7v976.cloudfront.net/cef/4280/linux_64/cef_binary.7z 

And downloaded somether here

https://github.com/ONLYOFFICE/build_tools/blob/master/scripts/core_common/modules/cef.py#L31

But if your platform is different from this list https://github.com/ONLYOFFICE/build_tools/blob/master/scripts/core_common/modules/cef.py#L16 there may be this error

**Comment by 1205469665** [comment]
**The requested address does not exist, and 404 cannot be accessed by me alone**

Extracting  cef_binary/Resources/locales/th.pak
Extracting  cef_binary/Resources/locales/tr.pak
Extracting  cef_binary/Resources/locales/uk.pak
Extracting  cef_binary/Resources/locales/vi.pak
Extracting  cef_binary/Resources/locales/zh-CN.pak
Extracting  cef_binary/Resources/locales/zh-TW.pak

Everything is Ok

Folders: 5
Files: 68
Size:       274107732
Compressed: 63659435
delete warning [file not exist]: ./cef_binary.7z.data
[fetch & build]: icu
svn: E000110: Unable to connect to a repository at URL 'https://github.com/unicode-org/icu/tags/release-58-2/icu4c'
svn: E000110: Error running context: Connection timed out
Error (svn): 1
Error (./make.py): 1
@ShockwaveNN

**Comment by 1205469665** [comment]
Is there a problem with the way the URL is written? It cannot be obtained correctly

    base.cmd("svn", ["export", "https://github.com/unicode-org/icu/tags/release-" + icu_major + "-" + icu_minor + "/icu4c", "./icu", "--non-interactive", "--trust-server-cert"])

**Comment by ShockwaveNN** [comment]
@1205469665 Please create a separate issue, since this is not an error original author mention, please do not hijack issues of other people with completely different errors

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
