### ISSUE TITLE
Error (gclient): 127 

### ISSUE THREAD

**Issue by 1205469665** [ONLYOFFICE/build_tools#368]
/root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/passphrase-encoding.html
/root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/proxy-certificates.html
/root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/RAND.html
/root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/RAND_DRBG.html
/root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/RSA-PSS.html
/root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/scrypt.html
/root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/SM2.html
/root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/ssl.html
/root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/X25519.html
/root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/X448.html -> /root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/X25519.html
/root/build_tools/scripts/../../core/Common/3dParty/openssl/build/linux_64/share/doc/openssl/html/man7/x509.html
[fetch & build]: v8
delete warning [file not exist]: ./v8.data
Cloning into 'depot_tools'...
remote: Sending approximately 40.89 MiB ...
remote: Counting objects: 7, done
remote: Finding sources: 100% (7/7)
remote: Total 45522 (delta 30769), reused 45519 (delta 30769)
Receiving objects: 100% (45522/45522), 40.91 MiB | 8.00 KiB/s, done.
Resolving deltas: 100% (30769/30769), done.
Checking connectivity... done.
Running depot tools as root is sad.
curl: (7) Failed to connect to chrome-infra-packages.appspot.com port 443: Connection timed out
/root/build_tools/scripts/../../core/Common/3dParty/v8/depot_tools/bootstrap_python3: line 32: bootstrap-2@3.8.10.chromium.20_bin/python3/bin/python3: No such file or directory
cat: /root/build_tools/scripts/../../core/Common/3dParty/v8/depot_tools/python3_bin_reldir.txt: No such file or directory
/root/build_tools/scripts/../../core/Common/3dParty/v8/depot_tools/vpython3: line 52: /root/build_tools/scripts/../../core/Common/3dParty/v8/depot_tools/.cipd_bin/vpython3: No such file or directory
Error (gclient): 127
Error (./make.py): 1

Ubuntu 14.04 What should I do about this error when compiling the source code

**Comment by ShockwaveNN** [comment]
> curl: (7) Failed to connect to chrome-infra-packages.appspot.com port 443: Connection timed out

Are you sure you got correctly working network connection?
You got some errors in other issue and I think those addresses may be blocked on innacasable in your location for any reason

I think this url is from v8 repo and we do not control this url

By the way does this command show any error on your host? For me it's fine

```
wget chrome-infra-packages.appspot.com
```
This download index.html

**Comment by ShockwaveNN** [comment]
How did your resolve your issue if anyone else find it?

P.S. It's very sad for me, that people just close issues without any comment or even basic thank you if our team somehow helped them (

**Comment by 1205469665** [comment]
是因为网络问题,设置了git 的网络代理 没有设置svn 的那个地址是使用的svn下载的,之前以为是用git 下载的,把网络改成全局的就可以了
