### ISSUE TITLE
Specifies whether linuX_ARM 64 is supported

### ISSUE THREAD

**Issue by 1205469665** [ONLYOFFICE/build_tools#369]
Specifies whether linuX_ARM 64 is supported 
The desktop version

**Comment by ShockwaveNN** [comment]
Currently we do not support any Linux arm64 on any products

More details here - https://github.com/ONLYOFFICE/DocumentServer/issues/152

We report it there as soon as any of our product start support this architecture. DocumentServer is our base product, so we start from DocumentServer, but currently there is no much progress

**Comment by jiriks74** [comment]
You can use nextcloud and document server, to have it on arm desktop devices. You can run the server (unofficially with qemu) on arm. If you know how to setup nextcloud, just install onlyoffice app in nextcloud settings and follow [this](https://github.com/ONLYOFFICE/DocumentServer/issues/152#issuecomment-834217879) to setup onlyoffice server on arm.
