### ISSUE TITLE
allthemesgen errors: Cannot read property 'length' of undefined  / Fatal error in v8::ToLocalChecked

### ISSUE THREAD

**Issue by jdelrue** [ONLYOFFICE/build_tools#371]
**Describe your problem**:
When building onlyoffice, the step "allthemesgen" ends with segfault

**Steps to reproduce the problem**:
Use current (main) build_tools and go through build process, or use this dockerfile:

```
FROM ubuntu:20.04 as builder

ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y update &&  \
    apt-get -y install git \
                       sudo \
			python3 \
			python

WORKDIR /root/

RUN git clone https://github.com/ONLYOFFICE/build_tools.git
RUN cd /root/build_tools/tools/linux/ && ./automate.py
RUN  cd  /root/build_tools/out/linux_64/onlyoffice/documentserver/ &&  LD_LIBRARY_PATH=${PWD}/server/FileConverter/bin server/tools/allthemesgen  --converter-dir="${PWD}/server/FileConverter/bin"   --src="${PWD}/sdkjs/slide/themes"   --output="${PWD}/sdkjs/common/Images"

```
build fails with error:
![image](https://user-images.githubusercontent.com/1687505/130913532-34208b70-8d28-42de-88d0-62fda92b8c4d.png)

**DocumentBuilder version**: master

**Installation method**:

**Operating system**: Linux Ubuntu/Docker

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
