### ISSUE TITLE
make: *** [sub--root-core-ASCOfficeDocxFile2-Linux-ASCOfficeDocxFile2Lib-pro-make_first-ordered] Error 2

### ISSUE THREAD

**Issue by 1205469665** [ONLYOFFICE/build_tools#374]
../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/../../../../ASCOfficePPTXFile/PPTXFormat/../Editor/././Drawing/Shapes/BaseShape/Common.h:357:17: warning: 'void NSStringUtils::CheckPathOn_Fill_Stroke(std::wstring&, bool&, bool&)' defined but not used [-Wunused-function]
     static void CheckPathOn_Fill_Stroke(std::wstring& strPath, bool& bFill, bool& bStroke)
                 ^
In file included from ../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/../DocxFormat/RId.h:37:0,
                 from ../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/../DocxFormat/IFileContainer.h:36,
                 from ../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/Xlsx.h:35,
                 from ../DocWrapper/ChartWriter.cpp:36:
../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/../DocxFormat/../XML/Utils.h:294:13: warning: 'int XmlUtils::GenerateInt()' defined but not used [-Wunused-function]
  static int GenerateInt()
             ^
In file included from ../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/../DocxFormat/File.h:38:0,
                 from ../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/../DocxFormat/UnknowTypeFile.h:36,
                 from ../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/../DocxFormat/IFileContainer.h:37,
                 from ../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/Xlsx.h:35,
                 from ../DocWrapper/ChartWriter.cpp:36:
../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/../DocxFormat/FileType.h:130:20: warning: 'const bool OOX::operator==(const OOX::FileType&, const wstring&)' defined but not used [-Wunused-function]
  static const bool operator ==(const FileType& file, const std::wstring& type)
                    ^
In file included from ../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/Worksheets/../Drawing/CellAnchor.h:42:0,
                 from ../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/Worksheets/../Drawing/Drawing.h:38,
                 from ../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/Worksheets/Worksheet.h:44,
                 from ../DocWrapper/ChartWriter.cpp:40:
../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/Worksheets/../Drawing/../../../../../ASCOfficePPTXFile/PPTXFormat/Logic/Shape.h:49:35: warning: 'SimpleTypes::Vml::SptType OOX::PrstGeom2VmlShapeType(SimpleTypes::EShapeType)' defined but not used [-Wunused-function]
  static SimpleTypes::Vml::SptType PrstGeom2VmlShapeType(SimpleTypes::EShapeType type) 
                                   ^
../DocWrapper/../../Common/DocxFormat/Source/XlsxFormat/Worksheets/../Drawing/../../../../../ASCOfficePPTXFile/PPTXFormat/Logic/Shape.h:220:35: warning: 'SimpleTypes::Vml::SptType OOX::PrstTx2VmlShapeType(SimpleTypes::ETextShapeType)' defined but not used [-Wunused-function]
  static SimpleTypes::Vml::SptType PrstTx2VmlShapeType(SimpleTypes::ETextShapeType type) 
                                   ^
make[1]: Leaving directory `/root/core/ASCOfficeDocxFile2/Linux'
make: *** [sub--root-core-ASCOfficeDocxFile2-Linux-ASCOfficeDocxFile2Lib-pro-make_first-ordered] Error 2
Error (make): 2
Error (./make.py): 1
Hello, what is the reason for this mistake

**Comment by ShockwaveNN** [comment]
Please add more details

1. This version of `build_tools` are you using (git commit of HEAD if you cloned from github)
2. Which is host os for build. Please note that we guarantee successful build only on Ubuntu 14.04
3. Do you checked Docker build instruction if this variant generate same error?

**Comment by 1205469665** [comment]
Is the version used, also used 14.04, should have no problem, but is reported this error

**Comment by 1205469665** [comment]
It worked the first time I compiled it, but failed the second time I executed it, again on the source system

**Comment by ShockwaveNN** [comment]
> but failed the second time I executed it, again on the source system

Maybe some files are incorrectly cleaned-up after first build

I think you should clone `build_tools` in new location and take a look once more

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
