### ISSUE TITLE
"err","data":-88    What does that mean?

### ISSUE THREAD

**Issue by 1205469665** [ONLYOFFICE/build_tools#382]
pubsub message start:{"type":7,"cmd":{"c":"save","id":"627a455a6aba4","userid":"uid-1632795066588","data":null,"title":"xxxxxxx.docx","outputformat":65,"outputpath":"output.docx","savetype":3,"saveindex":1,"status_info":-88,"savekey":"627a455a6aba4_5888","userconnectionid":"uid-16327950665881","nobase64":true},"output":{"type":"documentOpen","data":{"type":"save","status":"err","data":-88}},"needUrlKey":null,"needUrlMethod":null,"needUrlType":null}

**Comment by ShockwaveNN** [comment]
Hi, please add more details to your message

Did you compile DocumentServer
If so - please specify the commit of `build_tools` you've used, your host os

And describe in more detail how did you get this message? It's from websocket? Do you integrate documentServer with some dms?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
