### ISSUE TITLE
recipe for target '../../lib/libQt5Network.so.5.9.9' failed

### ISSUE THREAD

**Issue by liu-minjie** [ONLYOFFICE/build_tools#389]
**Describe your problem**:
I follow "https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx"
after i run  "./automate.py server",  finally i get:

collect2: error: ld returned 1 exit status
Makefile:582: recipe for target '../../lib/libQt5Network.so.5.9.9' failed
make[3]: *** [../../lib/libQt5Network.so.5.9.9] Error 1
make[3]: Leaving directory '/opt/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/src/network'
Makefile:272: recipe for target 'sub-network-make_first' failed
make[2]: *** [sub-network-make_first] Error 2
make[2]: Leaving directory '/opt/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/src'
Makefile:48: recipe for target 'sub-src-make_first' failed
make[1]: *** [sub-src-make_first] Error 2
make[1]: Leaving directory '/opt/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase'
Makefile:71: recipe for target 'module-qtbase-make_first' failed
make: *** [module-qtbase-make_first] Error 2
Error (make): 2

**build_tools base repo version**:
6.4.0
**Operating system**:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Compiler version**:

[qt.txt](https://github.com/ONLYOFFICE/build_tools/files/7341886/qt.txt)

**Comment by liu-minjie** [comment]
> Could you recheck for same error on Ubuntu 14.04? We mostly change it on this version, since it provide better compatibility with all versions

I change  to  Ubuntu 14.04.6
build_tools base repo version: 6.4.0

finnally i  get:

------------------------------------------
BUILD_PLATFORM: linux_64
------------------------------------------
make file: makefiles/build.makefile_linux_64
Project MESSAGE: linux-64
Project MESSAGE: linux_64/release
Project MESSAGE: current_makefile
Project MESSAGE: makefiles/build.makefile_linux_64
Project ERROR: Sub-project qmake file '/home/lmj/build_tools/../desktop-sdk/ChromiumBasedEditors/videoplayerlib/videoplayerlib.pro' is not exists.
Error (/home/lmj/build_tools/tools/linux/qt_build/Qt-5.9.9/gcc_64/bin/qmake): 3
Error (./make.py): 1

**Comment by liu-minjie** [comment]
> Could you try to start compilation not with `./automate.py server` but with `./automate.py` without options - it'll take not much time more, but seems problem with videoplayerlib should not be actual for that type of build

after `./automate.py`:

make[1]: *** [core_build/linux_64/release/obj/docxformatlib_logic.o] Error 1
make[1]: Leaving directory `/home/lmj/core/Common/DocxFormat/DocxFormatLib'
make: *** [sub--home-lmj-core-Common-DocxFormat-DocxFormatLib-DocxFormatLib-pro-make_first-ordered] Error 2
Error (make): 2
Error (./make.py): 1

**Comment by ShockwaveNN** [comment]
This is strange, because I've build master yesterday and it was fine

So I think 

1. you need to cleanup working dir
2. Make sure that build_tools is version `bdd4b7ee4518ca4848e0c3b5c469cb9890a96b46`

**Comment by liu-minjie** [comment]
> 1. Integrate DocumentServer into a separate product like nextcloud
> 2. Start any test example, for example [`nodejs` one](https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/nodejs)

it works, thanks!!!
