### ISSUE TITLE
How can sdkjs build sourcemap?

### ISSUE THREAD

**Issue by Malenconiaprincep** [ONLYOFFICE/build_tools#398]
**Do you want to request a *feature* or report a *bug*?**

question

**What is the current behavior?**

I wanted to build SDKJS sourcemap to locate errors after compression, but now I get compiler errors using closure-Compiler

**Comment by Malenconiaprincep** [comment]
Sorry, it's not a compilation error. Now, the closure-Compiler seems not to be optimized. When I modify gruntfile.js file, adding sourcemap will give me a compilation error. I would like to know how you track the error reported after compression

**Comment by ShockwaveNN** [comment]
I'm really do not understand what you're meaning, especially if you do not showing me any errors - is this errors in compilation, is this error while running compiled js code

**Comment by Malenconiaprincep** [comment]
Source.map.js is a way of debugging code on the front end, generating source.map.js when editing javascript code. You could look it
https://github.com/google/closure-compiler/wiki/Flags-and-Options

**Comment by ShockwaveNN** [comment]
I know what is sourcemap, but I still do not understand what is your error

And I think we got no official public guide how to use sourcmaps

**Comment by Malenconiaprincep** [comment]
I added create_source_map to closure_compile, and now it generates the corresponding sourcemap, but the sourcemap map is in the wrong place

**Comment by ShockwaveNN** [comment]
Sorry, I've no idea that to do

**Comment by Malenconiaprincep** [comment]
Could you please how does your online obfuscation code track and solve problems?

**Comment by ShockwaveNN** [comment]
Sorry, have no idea

Maybe @trofim24 will have free time to answer this question

**Comment by Malenconiaprincep** [comment]
ok, thanks you
