### ISSUE TITLE
Menu is not display

### ISSUE THREAD

**Issue by Revvz** [ONLYOFFICE/build_tools#409]
Hello! I assembled the office by manual
https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx. But unfortunately, it is impossible to use it, since icons are not displayed in my menu. Attaching photo. What to do about it? Or is it a build bug?
Thanks.
Build on Ubuntu 14.04
![onlyoffice bug](https://user-images.githubusercontent.com/56865086/142414179-688e939e-8131-4411-b077-93fbb42d61bc.jpg)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
