### ISSUE TITLE
Compiling stopped with error: AttributeError: 'module' object has no attribute 'make'

### ISSUE THREAD

**Issue by p294960570** [ONLYOFFICE/build_tools#418]
The attempt of compiling with "./automate.py" stopped with the following error:

Already up-to-date.
Traceback (most recent call last):
  File "./make.py", line 70, in <module>
    make_common.make()
  File "scripts/core_common/make_common.py", line 20, in make
    boost.make()
AttributeError: 'module' object has no attribute 'make'
Error (./make.py): 1

os: ubuntu14.04

Python 2.7.6

**Comment by p294960570** [comment]
all log

root@ubuntu:~/onlyoffice/build_tools/tools/linux# ./automate.py 
---------------------------------------------
build branch: master
---------------------------------------------
---------------------------------------------
build modules: desktop builder server
---------------------------------------------
[git] update: DocumentBuilder
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
Submodule path 'core': checked out '0c29e4d08e3dfbdd1739289bbab2cb8b928b8a26'
Submodule path 'desktop-sdk': checked out '522c3c6cffd1071a8246f12173604e4c25540f28'
Submodule path 'sdkjs': checked out '9af7d085bf0717f978ed5bfc3595e37746880aeb'
[git] update: core
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: plugin-thesaurus
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: web-apps
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: document-server-integration
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Submodule path 'web/documentserver-example/csharp-mvc/assets': checked out '2f519764cf838d9ffd18071bdef9137cf5fab936'
Submodule path 'web/documentserver-example/csharp/assets': checked out '2f519764cf838d9ffd18071bdef9137cf5fab936'
Submodule path 'web/documentserver-example/java-spring/src/main/resources/assets': checked out '2f519764cf838d9ffd18071bdef9137cf5fab936'
Submodule path 'web/documentserver-example/java/src/main/resources/assets': checked out '2f519764cf838d9ffd18071bdef9137cf5fab936'
Submodule path 'web/documentserver-example/nodejs/public/assets': checked out '2f519764cf838d9ffd18071bdef9137cf5fab936'
Submodule path 'web/documentserver-example/php/assets': checked out '2f519764cf838d9ffd18071bdef9137cf5fab936'
Submodule path 'web/documentserver-example/python/assets': checked out '2f519764cf838d9ffd18071bdef9137cf5fab936'
Submodule path 'web/documentserver-example/ruby/public/assets': checked out '2f519764cf838d9ffd18071bdef9137cf5fab936'
Already up-to-date.
Submodule path 'web/documentserver-example/csharp-mvc/assets': checked out 'd66cdf5b05313212e77567e12dfba18814383bd2'
Submodule path 'web/documentserver-example/csharp/assets': checked out 'd66cdf5b05313212e77567e12dfba18814383bd2'
Submodule path 'web/documentserver-example/java-spring/src/main/resources/assets': checked out 'd66cdf5b05313212e77567e12dfba18814383bd2'
Submodule path 'web/documentserver-example/java/src/main/resources/assets': checked out 'd66cdf5b05313212e77567e12dfba18814383bd2'
Submodule path 'web/documentserver-example/nodejs/public/assets': checked out 'd66cdf5b05313212e77567e12dfba18814383bd2'
Submodule path 'web/documentserver-example/php/assets': checked out 'd66cdf5b05313212e77567e12dfba18814383bd2'
Submodule path 'web/documentserver-example/python/assets': checked out 'd66cdf5b05313212e77567e12dfba18814383bd2'
Submodule path 'web/documentserver-example/ruby/public/assets': checked out 'd66cdf5b05313212e77567e12dfba18814383bd2'
[git] update: plugin-translator
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: dictionaries
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: sdkjs
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: plugin-highlightcode
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: core-fonts
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: server
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: desktop-sdk
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: plugin-photoeditor
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: plugin-mendeley
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: desktop-apps
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: document-templates
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: plugin-macros
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: plugin-zotero
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: plugin-youtube
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: plugin-ocr
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: plugin-speech
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
Traceback (most recent call last):
  File "./make.py", line 70, in <module>
    make_common.make()
  File "scripts/core_common/make_common.py", line 20, in make
    boost.make()
AttributeError: 'module' object has no attribute 'make'
Error (./make.py): 1

**Comment by ShockwaveNN** [comment]
Hi, this is strange

>   File "scripts/core_common/make_common.py", line 20, in make

Seems it doesn't like [this line](https://github.com/ONLYOFFICE/build_tools/blob/master/scripts/core_common/make_common.py#L20)

Have no idea why this is
Are you sure `build_tools` repo is fully cloned and has no modifications, like removing some files

What's the output of both
```
git status
```
and

```
git rev-parse HEAD
```

**Comment by p294960570** [comment]
There was a error before,
I reinstalled boost,
boost_ 1_ 55_ 0

```
root@ubuntu:~/onlyoffice/build_tools# git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	tools/linux/cef_binary.7z
	tools/linux/node_js_setup_10.x
	tools/linux/packages_complete
	tools/linux/qt-everywhere-opensource-src-5.9.9/
	tools/linux/qt_build/
	tools/linux/qt_source_5.9.9.tar.xz

nothing added to commit but untracked files present (use "git add" to track)
root@ubuntu:~/onlyoffice/build_tools# git  rev-parse HEAD
cf4cac94821133567437a06d634ec15d8da861cb
root@ubuntu:~/onlyoffice/build_tools# 
```

**Comment by ShockwaveNN** [comment]
I've rechecked on my pc and everything seems fine on that part:
```
Already on 'master'
Cloning into 'plugin-macros'...
Already on 'master'
Cloning into 'plugin-zotero'...
Already on 'master'
Cloning into 'plugin-youtube'...
Already on 'master'
Cloning into 'plugin-ocr'...
Already on 'master'
Cloning into 'plugin-speech'...
Already on 'master'
Cloning into 'boost_1_72_0'...
Note: checking out '789155d431930ebef4766550ed7bd09f62eac714'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Cloning into 'libs/accumulators'...
```

Maybe reason is you've used python2?
Not very good at python, but in Dockerfile I've used - [python3 is called](https://github.com/ONLYOFFICE/build_tools/blob/master/Dockerfile#L15) for script

**Comment by p294960570** [comment]
I reinstalled the os
This is a new error

```
Done.
> pkg@5.5.1
> Fetching base Node.js binaries to PKG_CACHE_PATH


> Warning Cannot resolve ''./' + configCommon.get('services.CoAuthoring.server.editorDataStorage')'
  /root/onlyoffice/server/build/server/DocService/sources/DocsCoServer.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve ''./' + config.get('storage.name')'
  /root/onlyoffice/server/build/server/Common/sources/storage-base.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Failed to make bytecode node10-x64 for file /snapshot/server/build/server/Common/node_modules/openpgp/dist/openpgp.js
prebuild-install WARN install No prebuilt binaries found (target=v10.24.1 runtime=node arch=x64 libc= platform=linux)
prebuild-install WARN install No prebuilt binaries found (target=v10.24.1 runtime=node arch=x64 libc= platform=linux)
> pkg@5.5.1
> Warning Cannot resolve ''./' + config.get('storage.name')'
  /root/onlyoffice/server/build/server/Common/sources/storage-base.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve ''./' + configCommon.get('services.CoAuthoring.server.editorDataStorage')'
  /root/onlyoffice/server/build/server/DocService/sources/DocsCoServer.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Failed to make bytecode node10-x64 for file /snapshot/server/build/server/Common/node_modules/openpgp/dist/openpgp.js
prebuild-install WARN install No prebuilt binaries found (target=v10.24.1 runtime=node arch=x64 libc= platform=linux)
prebuild-install WARN install No prebuilt binaries found (target=v10.24.1 runtime=node arch=x64 libc= platform=linux)
> pkg@5.5.1
> Warning Cannot resolve 'name'
  /root/onlyoffice/server/build/server/Metrics/node_modules/statsd/stats.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'name'
  /root/onlyoffice/server/build/server/Metrics/node_modules/statsd/stats.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
prebuild-install WARN install No prebuilt binaries found (target=v10.24.1 runtime=node arch=x64 libc= platform=linux)
npm WARN OnlineEditorsExampleNodeJS@4.1.0 license should be a valid SPDX license expression

added 215 packages from 141 contributors and audited 215 packages in 19.457s

2 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 moderate, 1 high, 1 critical)printInstalled
  run `npm audit fix` to fix them, or `npm audit` for details
Traceback (most recent call last):
  File "./make.py", line 95, in <module>
[git] update: DocumentBuilder
[git] update: core
[git] update: plugin-thesaurus
[git] update: web-apps
[git] update: document-server-integration
[git] update: plugin-translator
[git] update: dictionaries
[git] update: sdkjs
[git] update: plugin-highlightcode
[git] update: core-fonts
[git] update: server
[git] update: desktop-sdk
[git] update: plugin-photoeditor
[git] update: plugin-mendeley
[git] update: desktop-apps
[git] update: document-templates
[git] update: plugin-macros
[git] update: plugin-zotero
[git] update: plugin-youtube
[git] update: plugin-ocr
[git] update: plugin-speech
[fetch & build]: boost
[fetch & build]: cef
[fetch & build]: icu
[fetch & build]: openssl
[fetch & build]: v8
delete warning [file not exist]: ./v8.data
gcc major version: 4, use clang:false
gn gen out.gn/linux_64 --args="is_debug=false target_cpu=\"x64\" v8_target_cpu=\"x64\" v8_static_library=true is_component_build=false v8_use_snapshot=false is_clang=false use_sysroot=false treat_warnings_as_errors=false"
[fetch & build]: hunspell
------------------------------------------
BUILD_PLATFORM: linux_64
------------------------------------------
make file: makefiles/build.makefile_linux_64
copy warning [file not exist]: /root/onlyoffice/build_tools/scripts/../../sdkjs/common/HtmlFileInternal/AllFonts.js
delete warning [folder not exist]: /root/onlyoffice/build_tools/scripts/../../document-server-integration/web/documentserver-example/nodejs/node_modules
    build_server.make()
  File "scripts/build_server.py", line 62, in make
    base.cmd_in_dir(sync_rpc_lib_dir, "patch", ["-N", "-i", patch_file])
  File "scripts/base.py", line 332, in cmd_in_dir
    os.chdir(dir)
OSError: [Errno 2] No such file or directory: '/root/onlyoffice/build_tools/scripts/../../document-server-integration/web/documentserver-example/nodejs/node_modules/sync-rpc/lib'
---------------------------------------------
build branch: master
---------------------------------------------
---------------------------------------------
build modules: desktop builder server
---------------------------------------------
Error (./make.py): 1

```

**Comment by ShockwaveNN** [comment]
I think it's same error as here

https://github.com/ONLYOFFICE/build_tools/issues/414

But I was not able to reproduce it

Please provide some Dockerfile to be sure I can reproduce it, I have no idea why this happening unless some network issues or some major difference of some system libraries used

**Comment by p294960570** [comment]
i  follow [#414](https://github.com/ONLYOFFICE/build_tools/issues/414)
change the scripts/build_server.py and delete tools/linux/sync-rpc.patch
But it still didn't succeed

there is the new error

any idea?

```
In file included from ../BinWriter/../../Common/DocxFormat/Source/DocxFormat/Logic/../../../../../ASCOfficePPTXFile/PPTXFormat/Logic/./../../Editor/./XmlWriter.h:35:0,
                 from ../BinWriter/../../Common/DocxFormat/Source/DocxFormat/Logic/../../../../../ASCOfficePPTXFile/PPTXFormat/Logic/./../../Editor/BinWriters.h:38,
                 from ../BinWriter/../../Common/DocxFormat/Source/DocxFormat/Logic/../../../../../ASCOfficePPTXFile/PPTXFormat/Logic/./../WrapperFile.h:40,
                 from ../BinWriter/../../Common/DocxFormat/Source/DocxFormat/Logic/../../../../../ASCOfficePPTXFile/PPTXFormat/Logic/./../WrapperWritingElement.h:37,
                 from ../BinWriter/../../Common/DocxFormat/Source/DocxFormat/Logic/../../../../../ASCOfficePPTXFile/PPTXFormat/Logic/Ln.h:36,
                 from ../BinWriter/../../Common/DocxFormat/Source/DocxFormat/Logic/RunProperty.h:42,
                 from ../BinWriter/../../Common/DocxFormat/Source/DocxFormat/Logic/Paragraph.h:38,
                 from ../BinWriter/../../Common/DocxFormat/Source/DocxFormat/FtnEdn.h:41,
                 from ../BinWriter/../../Common/DocxFormat/Source/DocxFormat/Footnote.h:36,
                 from ../BinWriter/../../Common/DocxFormat/Source/DocxFormat/DocxFlat.h:36,
                 from ../BinWriter/BinWriters.h:36,
                 from ../BinWriter/BinWriters.cpp:32:
../BinWriter/../../Common/DocxFormat/Source/DocxFormat/Logic/../../../../../ASCOfficePPTXFile/PPTXFormat/Logic/./../../Editor/././Drawing/Shapes/BaseShape/Common.h:113:17: warning: ‘void NSStringUtils::ParsePath(const wstring&, std::vector<std::basic_string<wchar_t> >&)’ defined but not used [-Wunused-function]
     static void ParsePath(const std::wstring & strSource, std::vector<std::wstring>& ArrayResults)
                 ^
../BinWriter/../../Common/DocxFormat/Source/DocxFormat/Logic/../../../../../ASCOfficePPTXFile/PPTXFormat/Logic/./../../Editor/././Drawing/Shapes/BaseShape/Common.h:201:14: warning: ‘void NSStringUtils::ParsePath2(const wstring&, std::vector<std::basic_string<wchar_t> >*, bool)’ defined but not used [-Wunused-function]
  static void ParsePath2(const std::wstring & strSource, std::vector<std::wstring>* pArrayResults, bool bIsCleared = true)
              ^
../BinWriter/../../Common/DocxFormat/Source/DocxFormat/Logic/../../../../../ASCOfficePPTXFile/PPTXFormat/Logic/./../../Editor/././Drawing/Shapes/BaseShape/Common.h:357:17: warning: ‘void NSStringUtils::CheckPathOn_Fill_Stroke(std::wstring&, bool&, bool&)’ defined but not used [-Wunused-function]
     static void CheckPathOn_Fill_Stroke(std::wstring& strPath, bool& bFill, bool& bStroke)
                 ^
make[1]: Leaving directory `/root/onlyoffice/core/ASCOfficeDocxFile2/Linux'
make: *** [sub--root-onlyoffice-core-ASCOfficeDocxFile2-Linux-ASCOfficeDocxFile2Lib-pro-make_first-ordered] Error 2
[git] update: DocumentBuilder
[git] update: core
[git] update: plugin-thesaurus
[git] update: web-apps
[git] update: document-server-integration
[git] update: plugin-translator
[git] update: dictionaries
[git] update: sdkjs
[git] update: plugin-highlightcode
[git] update: core-fonts
[git] update: server
[git] update: desktop-sdk
[git] update: plugin-photoeditor
[git] update: plugin-mendeley
[git] update: desktop-apps
[git] update: document-templates
[git] update: plugin-macros
[git] update: plugin-zotero
[git] update: plugin-youtube
[git] update: plugin-ocr
[git] update: plugin-speech
[fetch & build]: boost
[fetch & build]: cef
[fetch & build]: icu
[fetch & build]: openssl
[fetch & build]: v8
gcc major version: 4, use clang:false
gn gen out.gn/linux_64 --args="is_debug=false target_cpu=\"x64\" v8_target_cpu=\"x64\" v8_static_library=true is_component_build=false v8_use_snapshot=false is_clang=false use_sysroot=false treat_warnings_as_errors=false"
[fetch & build]: hunspell
------------------------------------------
BUILD_PLATFORM: linux_64
------------------------------------------
make file: makefiles/build.makefile_linux_64
Error (make): 2
---------------------------------------------
build branch: master
---------------------------------------------
---------------------------------------------
build modules: desktop builder server
---------------------------------------------
Error (./make.py): 1
```

**Comment by ShockwaveNN** [comment]
> make: *** [sub--root-onlyoffice-core-ASCOfficeDocxFile2-Linux-ASCOfficeDocxFile2Lib-pro-make_first-ordered] Error 2


I remember same error at https://github.com/ONLYOFFICE/build_tools/issues/374

But seems we never figured it out

Only advice I have same as #374 - fully cleanup working folder and try to compile project anew

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
