### ISSUE TITLE
Build of either "server" or "all" on Ubuntu 14.04 LXC container fails

### ISSUE THREAD

**Issue by kommserv** [ONLYOFFICE/build_tools#421]
I worked against the latest `build_tools` repo commit: 
```
$ git rev-parse HEAD
cf4cac94821133567437a06d634ec15d8da861cb
```
**OS**: a freshly provisioned Ubuntu 14.04.6 LXC container (no security nesting, unprivileged, on Ubuntu 18.04 host if that matters)

**Compiler version**: 
```
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
```

Python2 and Python3 come installed on Ubuntu 14.04, note that `python -> python2` is already the default.
```
$ python3 --version
Python 3.4.3
$ python --version
Python 2.7.6
$ ll /usr/bin/python
lrwxrwxrwx 1 root root 9 Dec 21  2013 /usr/bin/python -> python2.7*
```

### Attempt to build only "server"

Lines beginning with hash (#) are meant as comments.

```
$ sudo apt update
# install fonts
$ sudo apt install fonts-dejavu fonts-liberation ttf-mscorefonts-installer fonts-crosextra-carlito fonts-takao-gothic fonts-opensymbol
# install nodejs
$ curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
$ sudo apt install nodejs
$ sudo npm install -g npm grunt-cli
# JRE (latest available in repos is 7, but the build script configures PPA for OpenJDK 11 by itself...)
$ sudo apt install java-common default-jdk default-jre default-jre-headless openjdk-7-jdk openjdk-7-jdk-headless openjdk-7-jre openjdk-7-jre-headless
# Redis
$ sudo apt install redis-server php5-redis php5-apcu
# install build dependencies
$ sudo apt install apt-transport-https autoconf2.13 build-essential ca-certificates cmake curl git libglib2.0-dev libglu1-mesa-dev libgtk-3-dev libpulse-dev libtool p7zip-full subversion gzip libasound2-dev libatspi2.0-dev libcups2-dev libdbus-1-dev libicu-dev libglu1-mesa-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libx11-xcb-dev libxcb* libxi-dev libxrender-dev libxss1 libncurses5 wget libcurl4-gnutls-dev libglib2.0-dev libgdk-pixbuf2.0-dev libgtkglext1-dev libatk1.0-dev libcairo2-dev libxml2-dev libxss-dev libgconf2-dev qt5-qmake qt5-default
# runtime dependencies
$ sudo apt install rabbitmq-server adduser libstdc++6 libxml2 libboost-regex-dev zlib1g libxss1 libcairo2 xvfb libxtst6 libasound2 libgconf-2-4 libcurl3
# install PostgreSQL database
$ sudo apt install postgresql
# build OODS using build_tools
$ mkdir ~/oods
$ cd ~/oods
$ git clone --recursive https://github.com/ONLYOFFICE/build_tools.git
$ cd build_tools/tools/linux
$ python3 automate.py server > ~/.cache/build-server.log 2>&1
```

I redirected both stdout and stderr to a log-file in order to be able to review any output, if needed (even with no history limits it quickly becomes tedious to scroll back in the terminal).
I kept an eye on the build progress by tailing the log file: `tail -f ~/.cache/build-server.log`.

The build fails after generating about 59k lines of output, with an error that is unambiguous:
```
Project ERROR: Sub-project qmake file '~/oods/build_tools/../desktop-sdk/ChromiumBasedEditors/videoplayerlib/videoplayerlib.pro' is not exists.
```

Like others have already reported, the entire directory `desktop-sdk` is actually non-existent.

+ https://github.com/ONLYOFFICE/build_tools/issues/82
+ https://github.com/ONLYOFFICE/build_tools/issues/104
+ https://github.com/ONLYOFFICE/build_tools/issues/363 

Issue #363 above suggests running `automate.py` **without any args** as a work-around. So I attempted that next.

### Attempt to build with no args

Created a new, freshly provisioned Ubuntu 14.04 container (everything the same as above). Installed the same dependencies. The only difference was the `automate.py` call, now lacking any arguments:
```
$ python3 automate.py > ~/.cache/build-all.log 2>&1
```

Just as before, I have saved the full log. This time it emits nearly 400k lines before stopping with a rather more unclear reason:
```
Running "clean:server" (clean) task
Verifying property clean.server exists in config...OK
Files: [no src] -> server
Options: force, no-write=false
>> 0 paths cleaned.

Running "mkdir" task

Running "mkdir:server" (mkdir) task
Verifying property mkdir.server exists in config...OK
File: [no files]
Options: mode=null, create=["./build/server"]
Options: mode=null, create=["./build/server"]
Creating "./build/server"...ERROR
>> Error: Unable to create directory "./build/server" (Error code: ERR_INVALID_ARG_VALUE).
Warning: Mkdir operation failed. Use --force to continue.

Aborted due to warnings.
[git] update: DocumentBuilder
[git] update: core
[git] update: plugin-thesaurus
[git] update: web-apps
[git] update: document-server-integration
[git] update: plugin-translator
[git] update: dictionaries
[git] update: sdkjs
[git] update: plugin-highlightcode
[git] update: core-fonts
[git] update: server
[git] update: desktop-sdk
[git] update: plugin-photoeditor
[git] update: plugin-mendeley
[git] update: desktop-apps
[git] update: document-templates
[git] update: plugin-macros
[git] update: plugin-zotero
[git] update: plugin-youtube
[git] update: plugin-ocr
[git] update: plugin-speech
[fetch & build]: boost
delete warning [file not exist]: ./boost.data
[fetch & build]: cef
delete warning [file not exist]: ./cef_binary.7z.data
[fetch & build]: icu
[fetch & build]: openssl
delete warning [file not exist]: ./openssl.data
[fetch & build]: v8
delete warning [file not exist]: ./v8.data
gcc major version: 4, use clang:false
gn gen out.gn/linux_64 --args="is_debug=false target_cpu=\"x64\" v8_target_cpu=\"x64\" v8_static_library=true is_component_build=false v8_use_snapshot=false is_clang=false use_sysroot=false treat_warnings_as_errors=false"
[fetch & build]: hunspell
------------------------------------------
BUILD_PLATFORM: linux_64
------------------------------------------
make file: makefiles/build.makefile_linux_64
copy warning [file not exist]: ~/oods/build_tools/scripts/../../sdkjs/common/HtmlFileInternal/AllFonts.js
Error (grunt): 6
install dependencies...
Installed Node.js version: 14.16
OK
install qt...
---------------------------------------------
build branch: master
---------------------------------------------
---------------------------------------------
build modules: desktop builder server
---------------------------------------------
Error (./make.py): 1
```

I could identify no previous issues or commits regarding the failed `mkdir` operation, I don't know if it's relevant.
As for the `../sdkjs/common/` directory, it contained multiple files and folders but not any folder named `HtmlFileInternal`. It seems this copy operation was [introduced with this commit](https://github.com/ONLYOFFICE/build_tools/commit/8a0ee8bdd7806b7802a60add5cdb2ca921d87b79) by @K0R0L.

I understand this project does not officially support newer Ubuntu releases, only 14.04. So what could I be doing wrong? Have I missed some dependency or some configuration necessary before starting the build? I assume I'm doing something wrong, since the latest commit has been around for over two months.

Could it be an LXC container issue (I have been bitten by those before...)? Like I mentioned up top, I have used unprivileged containers, and did not enable security nesting. I don't expect lack of privilege to be an issue, but I have learnt that security nesting is necessary for MariaDB/MySQL systemd service to run (but I'm not sure how lack of systemd affects that). In any case, I checked `systemctl status postgresql@9.5.service` on an Ubuntu 16.04 container created the same way and it reported no issues. But then again, I would not suspect that lack or not of postgresql should affect the build step (later configuration, certainly, but not the build)?

I would not mind sharing the full log files, but they are about 20MB and 50MB large, respectively, so I'd be glad for any suggestions on *how* to best share them if there's interest.

**Comment by ShockwaveNN** [comment]
Hi, thanks for detailed description

Several ideas:

> >> Error: Unable to create directory "./build/server" (Error code: ERR_INVALID_ARG_VALUE).

1. I never saw an error like that and my first thought maybe there is some limits on LXC container size? Because build size is rather big

2. Seems that it happened on 
https://github.com/ONLYOFFICE/server/blob/master/Gruntfile.js#L93
https://github.com/ONLYOFFICE/server/blob/master/package.json#L38

On those lines

Maybe it has something to do that seems that this folder can be created on `root` level

3. Also I saw that you've using `Installed Node.js version: 14.16` - could you try to install not the latest v14.16 but `v10.24.1` - maybe it has something to do with nodejs
4. `I would not mind sharing the full log files, but they are about 20MB and 50MB large,` - I don't think we will found any interesting information in those logs, but you can archive them as zip and they will be rather small and attach to github

**Comment by kommserv** [comment]
Thanks for your quick answer, you really helped me out there!

The issue was indeed caused by the NodeJS version, and after I used `v10.24.1` like you suggested (and `npm v6.14.12`) it ultimately worked (subsequently experienced issue #414, but the suggested patch worked).

There were a few more snags before it worked, so I wrote it all down as an Ansible role while working them out. [Feel free to look it over](https://github.com/kommserv/onlyoffice-docs-build) (if you're familiar with Ansible playbooks, perhaps even run it), and hopefully the comments and the mostly easy-to-read YAML is easy enough for anyone to decipher and learn from. I don't make any claims of being knowledgeable, mind you - I'm mostly feeling my way around. Any suggestions on improvements will be gracefully accepted and acknowledged.

It turned out to be unrelated to LXC container size (I used the `dir` backend, which apparently means that the container uses whatever space the host has).

I have included a few log files (one successful, and a couple for different errors) in the Ansible role's repo. 

I think we can close this issue? Even though building just the `server` component still fails with an error about `videoplayer.lib`, but that's already been reported in #82 (perhaps that issue should be reopened). But building all components (i.e., without any arguments) worked, and it only costs some extra time and disk space.

**Comment by ShockwaveNN** [comment]
Thanks for you investigation

I'm peronally not familiar with Ansible much, but I show this to our DevOps team, maybe they could use some of code snippets in future

> that's already been reported in #82 

We're nearly at release of v7.0.0 and I think I'll recheck this issue after that and reopen it again, really bad luck with this issue

> it only costs some extra time and disk space.

As I once have a talk with our dev team - there is a little to save by building only `desktop` or `server` without other components, since all base framework is the same and 95% of time building - took by base framework

> I think we can close this issue?

I think so, thanks again
