### ISSUE TITLE
【7.0.0】How to build a docker image after modifying the source code

### ISSUE THREAD

**Issue by wpmineq** [ONLYOFFICE/build_tools#424]
How to build a docker image after modifying the source code and recompiling it? 

I hope you can provide the documentation. Thank you very much. 

**build_tools base repo version**: releasev/7.0.0

**Operating system**: ubuntu

**Compiler version**: releasev/7.0.0

**Comment by ShockwaveNN** [comment]
Or of couse use official instruction "How to run it"
https://github.com/ONLYOFFICE/build_tools#installing-and-configuring-document-server-dependencies

**Comment by wpmineq** [comment]
> We don't have official documentation, but you can take a look at my unofficial repo which used to run DocumentServer after complication
> 
> https://github.com/ONLYOFFICE-QA/onlyoffice-documentserver-run-compiled

Thank you for your reply. Since the release of the official version of v7.0.0, my problem has been solved.
