### ISSUE TITLE
Compile error: Node.js version cannot be less 10.20

### ISSUE THREAD

**Issue by adriangibanelbtactic** [ONLYOFFICE/build_tools#427]
**Describe your problem**:

Building OnlyOffice does not complete. Probably because `Node.js version cannot be less 10.20`.

The error shown is the following one:
```
[fetch & build]: boost
delete warning [file not exist]: ./boost.data
[fetch & build]: cef
delete warning [file not exist]: ./cef_binary.7z.data
[fetch & build]: icu
[fetch & build]: openssl
delete warning [file not exist]: ./openssl.data
[fetch & build]: v8
delete warning [file not exist]: ./v8.data
gcc major version: 4, use clang:false
gn gen out.gn/linux_64 --args="is_debug=false target_cpu=\"x64\" v8_target_cpu=\"x64\" v8_static_library=true is_component_build=false v8_use_snapshot=false is_clang=false use_sysroot=false treat_warnings_as_errors=false"
[fetch & build]: hunspell
------------------------------------------
BUILD_PLATFORM: linux_64
------------------------------------------
make file: makefiles/build.makefile_linux_64

install dependencies...
Node.js version cannot be less 10.20
Reinstall
install qt...
---------------------------------------------
build branch: 
---------------------------------------------
---------------------------------------------
build modules: desktop builder server
---------------------------------------------
Error (./make.py): 1
```

**Steps to reproduce the problem**:
Prepare your system:
```
sudo apt-get update
 sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io
```
Try to build OnlyOffice:
```
cd /root
git clone \
    --depth=1 \
    --recursive \
    https://github.com/ONLYOFFICE/build_tools.git \
    /root/build_tools_oo
cd /root/build_tools_oo
mkdir out
docker run -v $(pwd)/out:/build_tools/out onlyoffice-document-editors-builder /bin/bash -c 'cd tools/linux && python3 ./automate.py'
```

**build_tools base repo version**:
master ( `v7.0.1.2` )

**Operating system**:
Debian 11 Netinst
**Compiler version**:
Whatever comes by default with the default Dockerfile

**Extra information**

I might try to workaround this compiling problem by bypassing the external development tools build.

Adding `base.set_env('NODE_ENV', 'production')` in `build_js.py` might do the trick as I did in https://github.com/btactic/build_tools/commit/a51685f373bcb9391292dbad02497c0736a3f026 .

Even if this workaround works (Not tested yet) it would be nice we would be able to build this out of the box without having to modify the source code.

Thank you for any insights you can give me.

**Comment by ShockwaveNN** [comment]
Hm, this is strange, because two days ago I compiled it from master via Docker and everything was fine 

I was having some message about `Node.js version cannot be less 10.20` but it was on some end steps and seems not making any harm

Are you sure that result product is working fine?

I think it's may be relate to that on clear system of Ubuntu 14.04 nodejs by default instruction installing not the latest version of v10.23 but like v10.18 or something like this, but it's the problem on nodejs script side

You can try to change baseimage from `FROM ubuntu:14.04` to `FROM ubuntu:20.04` and see if it helps

**Comment by adriangibanelbtactic** [comment]
> Hm, this is strange, because two days ago I compiled it from master via Docker and everything was fine
> 
> I was having some message about `Node.js version cannot be less 10.20` but it was on some end steps and seems not making any harm

Ok.

> Are you sure that result product is working fine?

I am sure that `out` directory is empty. So it's not building anything at all.

> I think it's may be relate to that on clear system of Ubuntu 14.04 nodejs by default instruction installing not the latest version of v10.23 but like v10.18 or something like this, but it's the problem on nodejs script side
> 
> You can try to change baseimage from `FROM ubuntu:14.04` to `FROM ubuntu:20.04` and see if it helps

Well, I use whatever it's default in your Dockerfile which it's ubuntu:14.04.

If my workaround which I'm applying thanks to: `-e NODE_ENV='production'` does not work as expected I will test your suggestion about using `ubuntu:20.04` in the Dockerfile.

Thank you very much for the feedback.

**Comment by ShockwaveNN** [comment]
> I am sure that out directory is empty. So it's not building anything at all.

Could you try to do how I'm usually do it

1. `cd build_tools`
2. `git checkout master -f && git pull`
3. `rake build` - it require `ruby`'s rake but inside `Rakefile` commands are rather straightforward

And this definitely resulted builder product in `out` folder

**Comment by adriangibanelbtactic** [comment]
Well, I am checking the full log again and I'm seeing this error which I had overlooked:
```
make[1]: Leaving directory `/core/ASCOfficePPTXFile/PPTXLib/Linux/PPTXFormatLib'                                              
make: *** [sub--core-ASCOfficePPTXFile-PPTXLib-Linux-PPTXFormatLib-PPTXFormatLib-pro-make_first-ordered] Error 2              
Error (make): 2[git] update: document-server-integration 
```
so, it might not be a problem about nodejs version after all.

Maybe should I `git pull` to get latest version?

Do you know if this PPTX problem it's something fixed recently?

I'm only interested on building `server` BTW. I try to build everything because back in the day (more than 6 months ago) you recommended to build everything even if you only were interested in the `server` part. Is there any improvement on that?

Thank you.

**Comment by ShockwaveNN** [comment]
> so, it might not be a problem about nodejs version after all.

Seems so

https://github.com/ONLYOFFICE/build_tools/issues/394

Looks similar and we never 100% detected but seems that it was out of memory error, our soft require a lot of memory to compile, I advice to use at least 8gb RAM with 8gb swap

I'm personally using 16gb machine to test compilateion and it always work fine

>  if you only were interested in the server part. Is there any improvement on that?

No there is not, because as I'm sad - DesktopEditors and DocumentServer use almost same components, so building only one of them differs only on packaging step, not on `core` compilation

**Comment by adriangibanelbtactic** [comment]
> Looks similar and we never 100% detected but seems that it was out of memory error, our soft require a lot of memory to compile, I advice to use at least 8gb RAM with 8gb swap
> 
> I'm personally using 16gb machine to test compilateion and it always work fine

I'm using 4gb RAM with no swap. And /var/log/messages say that cc1plus was killed because of an 'Out of memory' error.

Unless `-e NODE_ENV='production'` magically requires much less RAM I think it's time to upgrade my build machine VPS specs.

Thank you!

**Comment by ShockwaveNN** [comment]
> Unless -e NODE_ENV='production' magically requires much less RAM

I think it may be

You can try to add swap to yur system - I think this may be enough without increasing RAM

**Comment by adriangibanelbtactic** [comment]
Increasing RAM fixed the problem.

There's another problem on your build process. It should stop when an error happens. So that you know where the error is and that way you don't have to scroll way back up to find the error. Otherwise you can think that you have another error when it is not an error.

I'm not opening a new issue for this particular issue.

Anyways, as I said above, my problem is gone when I increase my RAM. So I'll close this issue.

Thank you again.

**Comment by ShockwaveNN** [comment]
> So that you know where the error is and that way you don't have to scroll way back up to find the error. Otherwise you can think that you have another error when it is not an error.

Yeah I agree that this sometimes happens and this is not right. But I was not able to fully reproduce this situation - when I deliberately change some line to be broken and build process is not stopped on that line
