### ISSUE TITLE
Remove my_bool from qsql_mysql.cpp

### ISSUE THREAD

**Issue by bhlevca** [ONLYOFFICE/build_tools#462]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Linux (RPM package)

### Version information

latest from sources

### Expected Behavior

The source for Linux does not compile with MySQL 8.0.  `my_bool `does not exist, it has bee replaced everywhere with `bool`

Replace `my_bool` with `bool` and it will compile just fine.

### Actual Behavior

does not compile

**Comment by bhlevca** [comment]
> # gcc --version
> gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0

No wonder that you don't get the errors. Casting void* to everything is no longer permitted. 
Your versions are ancient and no longer supported. Please update to Ubuntu 20.04 or even better in a week Ubuntu 22.04 will be available Ubuntu 16.04 is no longer supported LTS version. It expired lat year as Ubuntu LTS version are supported only for 5 years.  

also gcc is now at 9.3 and you are using the obsolete 5.4 which is not up to the latest standard.

**Comment by ShockwaveNN** [comment]
I understand your message and partly agree with that but we got good reason to use Ubuntu 14 as our build servers

1. By some of our contracts we need to support old versions of Linuxes, some of them based on Ubuntu 14.04 
And have Glibc 2.19 as a system base
If we build the same executable on a newer version of the system with newer Glibc - it simply will not start, so we use the oldest one to be compatible with most system

2. Proper way to solve this problem - to have a different build environment for each popular version of Glibc and this is a good solution, but right now we have no manpower to support it

So we choose the lesser of two evils - build based on oldest Ubuntu we can get our hands

We got docker to simplify this process https://github.com/ONLYOFFICE/build_tools#using-docker

It will result proper build on the newer versions of Ubuntu

But if you really need to build it using latest and greatest version of GCC -  I think you're on your own, I don't think I can help you

**Comment by bhlevca** [comment]
I understand what you are saying and partly agree, but what I don't understand is how can you have contracts for using a distro that is not supported by its maker. You use Ubuntu 16 and not 14 as you said, and support for it ended last year.

I am going to look at the docker option, but I feel that using unsupported software is not only wrong but plainly dangerous. So many  dangerous bugs in the kernel have been fixed in the past year.

**Comment by ShockwaveNN** [comment]
>  I don't understand is how can you have contracts for using a distro that is not supported by its maker. 

I don't think I can disclosure contract information, but seems you got very optimistic views in some big enterprise organizations, that nobody using old software

> I feel that using unsupported software is not only wrong but plainly dangerous

If you find out some real security problems with our build process (not in theory, but some practical use)  - feel free to report them to security@onlyoffice.com, we got some bug bounty program

**Comment by bhlevca** [comment]
> If you find out some real security problems with our build process (not in theory, but some practical use) - feel free to report them to [security@onlyoffice.com](mailto:security@onlyoffice.com), we got some bug bounty program

It is not about your software but about kernel as I said above and you probably missed. Old, unsupported systems can be hacked. If you need a recent example:
https://www.zdnet.com/article/nasty-linux-kernel-bug-found-and-fixed

I personally don't use such systems, but if corporations are cheap and do it there's no wonder that you hear about breaches and data compromised all the time. Your comments explain it.

**Comment by bhlevca** [comment]
So yes, your machines that use the old kernel if they are connected to the internet they could be hacked

**Comment by ShockwaveNN** [comment]
Thanks, we are aware of these risks and we do everything so our machines will be no hacked )

We gladly receive any report of any practical vulnerability we got, but right now this talk is only theoretical - we may have some, but most of our products are build inside docker containers this are destroyed after usage so I don't think it's very dangerous

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
