### ISSUE TITLE
error on compiling 

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/build_tools#467]
**Do you want to request a *feature* or report a *bug*?**
Bug?

**What is the current behavior?**
./automate.py 

make: *** [Makefile:75: module-qtbase-make_first] Error 2
Error (make): 2

"./automate.py server" does not wok either  

what i'm missing? 

This error cames after second "./automate.py"
```
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: .pch/Qt5OpenGL: No such file or directory
compilation terminated.
make[3]: *** [Makefile:4201: .obj/qgl.o] Error 1
make[3]: *** Waiting for unfinished jobs....
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: .pch/Qt5OpenGL: No such file or directory
compilation terminated.
make[3]: *** [Makefile:4295: .obj/qglcolormap.o] Error 1
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: .pch/Qt5OpenGL: No such file or directory
compilation terminated.
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Steps:
https://helpcenter.onlyoffice.com/de/installation/docs-community-compile.aspx

**Operating System:**
Debian 11

**Comment by hahaxd35** [comment]
do you may know whats missing? or witch versions from libraries  i need?

**Comment by ShockwaveNN** [comment]
Sorry, I don't know, I think you can google out this error, since it's not an ONLYOFFICE problem but may be a problem with old QT version compilation on newer platform

Or you can try to update QT to latest version, replacing link I've mention in previous message, but you're on your own, I've never tried it

**Comment by hahaxd35** [comment]
i thought this script was from ONLYOFFICE, but it is not, sorry

**Comment by ShockwaveNN** [comment]
It's our script, but again - we never checked compilation on Debian, we compile all our products on Ubuntu and they work fine on all other systems

**Comment by hahaxd35** [comment]
dont know how to do PR.
[automate.py.zip](https://github.com/ONLYOFFICE/build_tools/files/8728542/automate.py.zip)
changed Versionnumbers and thow some options out that was not supported anymore


and did some changes, that "make" will not download all file again ( that will revers any changes in source code)

**Comment by ShockwaveNN** [comment]
> dont know how to do PR.

We still not ready to merge any PR with update of Qt because we may loose compatibility with some *really* old system which we need to support by our contracts
