### ISSUE TITLE
error 2

### ISSUE THREAD

**Issue by weiboboCN** [ONLYOFFICE/build_tools#471]
environment :ubuntu14.04 （wsl2 docker）
1: sudo apt-get install -y python
2:  git clone https://github.com/ONLYOFFICE/build_tools.git  
3: cd build_tools/tools/linux
4: ./automate.py server 
error occurred during step4 
detail：
static void CheckPathOn_Fill_Stroke(std::wstring& strPath, bool& bFill, bool& bStroke)
                 ^
make[1]: Leaving directory `/root/core/ASCOfficeDocxFile2/Linux'
make: *** [sub--root-core-ASCOfficeDocxFile2-Linux-ASCOfficeDocxFile2Lib-pro-make_first-ordered] Error 2
Error (make): 2
Error (./make.py): 1
<img width="1418" alt="WX20220527-182705@2x" src="https://user-images.githubusercontent.com/23450893/170682521-d8cee7e8-3ef5-48f6-a16b-de791ef3d2cc.png">

**Comment by ShockwaveNN** [comment]
> 4: ./automate.py server


Could you try to build it not only server but all components, like `./automate.py`

Seems that several times we got problems building only part of project, but if all is build (which add little more time) - everything will be fine

**Comment by verydemo** [comment]
I had a similar error.
![image](https://user-images.githubusercontent.com/29354679/173020059-69613f0b-afe3-49ff-9d13-89ad5eef736e.png)

**Comment by ShockwaveNN** [comment]
@verydemo 

Did you run this?

> Could you try to build it not only server but all components, like ./automate.py

**Comment by verydemo** [comment]
I'm compiling.  ./automate.py
@ShockwaveNN

**Comment by verydemo** [comment]
![image](https://user-images.githubusercontent.com/29354679/173028591-477280d6-7fbc-4fc1-aef3-52ef1493a946.png)
file not exist.

**Comment by ShockwaveNN** [comment]
Yeah, I see this file do not exists

Do you trying to compile from master? Any modification to code? How can I reproduce your problem?

**Comment by verydemo** [comment]
Thanks. I recompiled it and it worked.
@ShockwaveNN

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
