### ISSUE TITLE
No route to host during compilation

### ISSUE THREAD

**Issue by spacezmonkey** [ONLYOFFICE/build_tools#476]
**Describe your problem**:
During compilation, I face the following error 
```
Fail to connect to onlyoffice.github.io port 433: No route to host 
Error (Curl) : 7
Error (./make.py): 1
```
*Be clear in your description of the problem.
Open an issue with a descriptive title and a summary in complete sentences.*
No route to host during compilation using build tool.

*Use the template below when reporting bugs. Please, make sure that
you're fetched latest master of build_tools and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

*Before filing the ticket you should replace all cursive text with your own words.*

**Steps to reproduce the problem**:
![image](https://user-images.githubusercontent.com/73033222/171546889-46e433b7-4f85-4838-84fa-dd14230abca7.png)

*Please make sure your error can be reproduced, Docker can be a great help*

**build_tools base repo version**:

**Operating system**:
Ubuntu 14.04 Desktop version
**Compiler version**:

**Comment by ShockwaveNN** [comment]
Hi, this literally mean that onlyoffice.github.io cannot be accessed

Maybe it's a simple network error or maybe github.io is blocked in your country

**Comment by spacezmonkey** [comment]
@ShockwaveNN you are true...i cannot even access github.io using web browser   =(

**Comment by ShockwaveNN** [comment]
In that case - you VPN or something like this, I'll close this issue but feel free to report any other problems
