### ISSUE TITLE
Can´t compile for local server due to ERROR (./make.py)

### ISSUE THREAD

**Issue by Kowalski2022** [ONLYOFFICE/build_tools#479]
Using docker image on Ubuntu 16.04.

Commands used:
mkdir out
docker build --tag onlyoffice-document-editors-builder .
docker run -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder

Results:
```
delete warning [file not exist]: ./boost.data
[fetch & build]: cef
delete warning [file not exist]: ./cef_binary.7z.data
[fetch & build]: icu
[fetch & build]: openssl
delete warning [file not exist]: ./openssl.data
[fetch & build]: v8
delete warning [file not exist]: ./v8.data
gcc major version: 5, use clang:false
gn gen out.gn/linux_64 --args="is_debug=false target_cpu=\"x64\" v8_target_cpu=\"x64\" v8_static_library=true is_component_build=false v8_use_snapshot=false is_clang=false use_sysroot=false treat_warnings_as_errors=false"
Error (ninja): 1
install dependencies...
Node.js version cannot be less 10.20
Reinstall
install qt...
---------------------------------------------
build branch: master
---------------------------------------------
---------------------------------------------
build modules: desktop builder server
---------------------------------------------
Error (./make.py): 1
```

**Comment by ShockwaveNN** [comment]
I don't see a specific error in your logs, but I think this mean probably one of two thing - you got no RAM left or you got no disk space left

**Comment by Kowalski2022** [comment]
I´m running it on a server that is configured with 300GB hard disk and 8GB RAM. In my server stats I can see maxium usage of memory 7.69% and still have 90% of disk free. I'm in Brazil, and don't know about blocking resources, since I could compile full code at Jun 9. I tried again in another virtual machine with same config since then and always got this  Error (./make.py): 1 and Error (ninja): 1.Since JUN 10 I tried using docker and using automate.py script and always got same message Error (./make.py). 
Will try again now and save full log, so I can attach it for you.

**Comment by Kowalski2022** [comment]
[103/1493] CXX obj/v8_base/asm-parser.o
FAILED: obj/v8_base/asm-parser.o
g++ -MMD -MF obj/v8_base/asm-parser.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIU$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[104/1493] CXX obj/v8_base/builtins-debug.o
FAILED: obj/v8_base/builtins-debug.o
g++ -MMD -MF obj/v8_base/builtins-debug.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHR$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[105/1493] CXX obj/v8_base/ast-value-factory.o
FAILED: obj/v8_base/ast-value-factory.o
g++ -MMD -MF obj/v8_base/ast-value-factory.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -D$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[106/1493] CXX obj/v8_base/arguments.o
FAILED: obj/v8_base/arguments.o
g++ -MMD -MF obj/v8_base/arguments.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[107/1493] CXX obj/v8_base/api-natives.o
FAILED: obj/v8_base/api-natives.o
g++ -MMD -MF obj/v8_base/api-natives.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMI$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[108/1493] CXX obj/v8_base/assembler.o
FAILED: obj/v8_base/assembler.o
g++ -MMD -MF obj/v8_base/assembler.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[109/1493] CXX obj/v8_base/ast-expression-rewriter.o
FAILED: obj/v8_base/ast-expression-rewriter.o
g++ -MMD -MF obj/v8_base/ast-expression-rewriter.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LO$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[110/1493] CXX obj/v8_base/allocation-site-scopes.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[111/1493] CXX obj/v8_base/ast-function-literal-id-reindexer.o
FAILED: obj/v8_base/ast-function-literal-id-reindexer.o
g++ -MMD -MF obj/v8_base/ast-function-literal-id-reindexer.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROW$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[112/1493] CXX obj/v8_base/asm-js.o
FAILED: obj/v8_base/asm-js.o
g++ -MMD -MF obj/v8_base/asm-js.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BU$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[113/1493] CXX obj/v8_base/ast-numbering.o
FAILED: obj/v8_base/ast-numbering.o
g++ -MMD -MF obj/v8_base/ast-numbering.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHRO$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[114/1493] CXX obj/v8_base/address-map.o
FAILED: obj/v8_base/address-map.o
g++ -MMD -MF obj/v8_base/address-map.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMI$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[115/1493] ACTION //:js2c(//build/toolchain/linux:x64)
[116/1493] CXX obj/v8_base/bit-vector.o
[117/1493] CXX obj/v8_base/bootstrapper.o
FAILED: obj/v8_base/bootstrapper.o
g++ -MMD -MF obj/v8_base/bootstrapper.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROM$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[118/1493] CXX obj/v8_libbase/ieee754.o
[119/1493] CXX obj/v8_base/asm-types.o
[120/1493] CXX obj/v8_base/bignum-dtoa.o
[121/1493] CXX obj/v8_base/allocation.o
[122/1493] CXX obj/v8_base/ast-loop-assignment-analyzer.o
FAILED: obj/v8_base/ast-loop-assignment-analyzer.o
g++ -MMD -MF obj/v8_base/ast-loop-assignment-analyzer.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[123/1493] CXX obj/v8_base/compile-time-value.o
FAILED: obj/v8_base/compile-time-value.o
g++ -MMD -MF obj/v8_base/compile-time-value.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
[124/1493] CXX obj/v8_base/ast.o
FAILED: obj/v8_base/ast.o
g++ -MMD -MF obj/v8_base/ast.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[125/1493] CXX obj/v8_libplatform/trace-object.o
[126/1493] CXX obj/v8_base/context-slot-cache.o
FAILED: obj/v8_base/context-slot-cache.o
g++ -MMD -MF obj/v8_base/context-slot-cache.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[127/1493] CXX obj/v8_base/accessors.o
FAILED: obj/v8_base/accessors.o
g++ -MMD -MF obj/v8_base/accessors.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[128/1493] CXX obj/v8_libbase/cpu.o
[129/1493] CXX obj/v8_base/background-parsing-task.o
FAILED: obj/v8_base/background-parsing-task.o
g++ -MMD -MF obj/v8_base/background-parsing-task.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LO$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[130/1493] CXX obj/v8_base/opcodes.o
[131/1493] CXX obj/v8_base/scopes.o
FAILED: obj/v8_base/scopes.o
g++ -MMD -MF obj/v8_base/scopes.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BU$
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[132/1493] CXX obj/v8_base/operator.o
[133/1493] CXX obj/third_party/icu/icui18n/calendar.o
[134/1493] CXX obj/v8_base/operator-properties.o
[135/1493] CXX obj/v8_base/bignum.o
[136/1493] CXX obj/v8_base/node.o
[137/1493] CXX obj/testing/gmock/gmock/gmock-cardinalities.o
[138/1493] CXX obj/v8_libsampler/sampler.o
[139/1493] CXX obj/testing/gtest/gtest_main/gtest_main.o
[140/1493] CXX obj/testing/gmock/gmock/gmock-internal-utils.o
[141/1493] CXX obj/testing/gtest/gtest/gtest-port.o
[142/1493] CXX obj/testing/gmock/gmock/gmock-spec-builders.o
[143/1493] CXX obj/v8_base/builtins-call.o
[144/1493] CXX obj/v8_base/variables.o
[145/1493] CXX obj/v8_base/builtins-boolean.o
[146/1493] CXX obj/v8_base/builtins-arraybuffer.o
[147/1493] CXX obj/testing/gtest/gtest/gtest-printers.o
[148/1493] CXX obj/testing/gmock/gmock/gmock.o
[149/1493] CXX obj/v8_base/modules.o
[150/1493] CXX obj/testing/gmock/gmock_main/gmock_main.o
[151/1493] CXX obj/v8_base/builtins-api.o
[152/1493] CXX obj/testing/gmock/gmock/gmock-matchers.o
[**168/1493] CXX obj/v8_base/api.o
ninja: build stopped: subcommand failed.** 
[git] update: document-server-integration
[git] update: sdkjs
[git] update: desktop-apps
[git] update: document-templates
[git] update: DocumentBuilder
[git] update: plugin-highlightcode
[git] update: plugin-photoeditor
[git] update: plugin-mendeley
[git] update: plugin-macros
[git] update: plugin-youtube
[git] update: core
[git] update: plugin-translator
[git] update: sdkjs-forms
[git] update: plugin-zotero
[git] update: web-apps
[git] update: plugin-speech
[git] update: desktop-sdk
[git] update: plugin-thesaurus
[git] update: dictionaries
[git] update: core-fonts
[git] update: server
[git] update: plugin-ocr
[fetch & build]: boost
delete warning [file not exist]: ./boost.data
[fetch & build]: cef
delete warning [file not exist]: ./cef_binary.7z.data
[fetch & build]: icu
[fetch & build]: openssl
delete warning [file not exist]: ./openssl.data
[fetch & build]: v8
delete warning [file not exist]: ./v8.data
gcc major version: 5, use clang:false
gn gen out.gn/linux_64 --args="is_debug=false target_cpu=\"x64\" v8_target_cpu=\"x64\" v8_static_library=true is_component_build=false v8_use_snapshot=false is_clang=false use_sysroot=false treat_warnings_as_errors=false"
Error (ninja): 1
install dependencies...
Node.js version cannot be less 10.20
Reinstall
install qt...
---------------------------------------------
build branch: master

**Comment by ShockwaveNN** [comment]
This no good:

> g++: internal compiler error: Killed (program cc1plus)

Not sure why it failing, are you have enough SWAP? Maybe 8gb is not enough, because I've no idea why this happens, seems like g++ crashing for some reason

**Comment by Kowalski2022** [comment]
Increased memory for 16 gb. Let's try again.

**Comment by ShockwaveNN** [comment]
Google that error and a lot of messages [about memory limits](https://stackoverflow.com/questions/30887143/make-j-8-g-internal-compiler-error-killed-program-cc1plus)

Maybe even somehow your docker limiting memory by default or something like this

**Comment by Kowalski2022** [comment]
I looked into the second link, but my host system is linux based. I´m trying to compile without docker solution now, to see if we still get the same error. 
After doing a dmesg seems to be related to the first issue. After testing will let you know the results. Thanks.

**Comment by Kowalski2022** [comment]
I tried to disable OOMKiller, and recompile with same issue. Also I created a swap file and still get no success. So I changed my VM SO from Ubuntu 16.04 to Debian 11 and seems that everything started working fine. Just waiting the script to finish
