### ISSUE TITLE
这个是什么情况？

### ISSUE THREAD

**Issue by yanght1001** [ONLYOFFICE/build_tools#497]
root@733a713a126f:/build_tools/tools/linux# ./automate.py server
install qt...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   289  100   289    0     0    328      0 --:--:-- --:--:-- --:--:--   328
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error (curl): 60

**Comment by ShockwaveNN** [comment]
Hi, we only understand English so please use it in issues

Are you sure you've using latest master of project?
Because similar error was then we've used Ubuntu 14.04 as base image and it's not compatible with latest Let's Encrypt certs

**Comment by yanght1001** [comment]
yes,it's  Ubuntu 14.04,Maybe I'm in China,We are have  wall,You kown~~~Some URL fail

**Comment by ShockwaveNN** [comment]
> We are have wall,You kown

This may be since we've never tested the build process from inside China since we have no access to such server

But may general advice - check carefully for errors if buid failed and if there is some network issue - use some kind of vpn
