### ISSUE TITLE
Docker Compiling stop in  make.py

### ISSUE THREAD

**Issue by zzdx713** [ONLYOFFICE/build_tools#503]
**Describe your problem**:
[fetch & build]: boost
./bootstrap.sh: 1: ./bootstrap.sh: ./tools/build/src/engine/build.sh: not found
Building Boost.Build engine with toolset ... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
Error (./bootstrap.sh): 1
Error (./make.py): 1

*Be clear in your description of the problem.
Open an issue with a descriptive title and a summary in complete sentences.*

*Use the template below when reporting bugs. Please, make sure that
you're fetched latest master of build_tools and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

*Before filing the ticket you should replace all cursive text with your own words.*

**Steps to reproduce the problem**:

*Please make sure your error can be reproduced, Docker can be a great help*

**build_tools base repo version**:

**Operating system**:
centos
**Compiler version**:
lasted

**Comment by ShockwaveNN** [comment]
This is error is similar to

https://github.com/ONLYOFFICE/build_tools/issues/461
https://github.com/ONLYOFFICE/build_tools/issues/467
https://github.com/ONLYOFFICE/build_tools/issues/366

In all those cases cleaning up and full new compilation was a solution, or some other solution seems to helped

I think you should read all those carefully and figure it out, I think the problem will be same, but we didn't found out root case of those problems

**Comment by ShockwaveNN** [comment]
Another day, another using ignoring my help (

Closing it
