### ISSUE TITLE
certificate subject name (*.tllms.com) does not match target host name 'github.com'

### ISSUE THREAD

**Issue by chenconghe** [ONLYOFFICE/build_tools#519]
hello ,i compile with ./automate.py server,but i returned follow message:

build branch: 
---------------------------------------------
---------------------------------------------
build modules: server
---------------------------------------------
[git] update: core
Cloning into '/root/build_tools-master/scripts/../../core'...
fatal: unable to access 'https://github.com/ONLYOFFICE/core.git/': SSL: certificate subject name (*.tllms.com) does not match target host name 'github.com'
Error (git): 128
Error (./make.py): 1

what has the problem?

**Comment by ShockwaveNN** [comment]
I think this error has something to do with your DNS servers, or maybe something about proxy or other complicated setup

git seems cannot download code from GitHub, so you should read error carefully and analyze problem yourself, I'm 99% sure this is not a problem on our side, but on your network config

**Comment by ShockwaveNN** [comment]
It will be helpful for other user if you describe how did you've resolved the problem before closing the issue
