### ISSUE TITLE
Can't compile on local server - ubuntu 16.04

### ISSUE THREAD

**Issue by young-coder-vn** [ONLYOFFICE/build_tools#550]
**Describe your problem**:

**Steps to reproduce the problem**:
   apt-get update
   apt-get install -y python git
    git clone https://github.com/ONLYOFFICE/build_tools.git
    cd build_tools/tools/linux/
    ./automate.py server

**build_tools base repo version**: master or 7.2.1

**Operating system**: 16.04

**Compiler version**: master or 7.2.1
![image](https://user-images.githubusercontent.com/30200422/200111252-3817059a-dfa3-4ec6-bcbb-d39cdd975cd8.png)

**Comment by ShockwaveNN** [comment]
```
cd build_tools/tools/linux/
./automate.py
```

Try to run it like that

**Comment by young-coder-vn** [comment]
@ShockwaveNN : try again, but error like that. 

![image](https://user-images.githubusercontent.com/30200422/200113256-f70b4a22-6523-4c86-b2bb-099f76ec57e6.png)

**Comment by ShockwaveNN** [comment]
Try to cleanup working dir by reseting repo and try again, seems something inocrrectly cached

**Comment by ShockwaveNN** [comment]
I've checked once again using [default Docker](https://github.com/ONLYOFFICE/build_tools/blob/master/Dockerfile) and everything seems fine, so make sure that it works and compare with your setup

**Comment by young-coder-vn** [comment]
@ShockwaveNN : still with same error,
I spend too much time on build_tool, is there a way to build a local development environment?

**Comment by ShockwaveNN** [comment]
I don't know that are you doing wrong but I've checked docker version and it compiled fine yesterday

So please provide detailed step-by-step instruction how did you used compilation in docker

**Comment by young-coder-vn** [comment]
Try again with docker. still error.
This is my step:
 1982  08/11/22 14:08:39 git clone https://github.com/ONLYOFFICE/build_tools.git
 1983  08/11/22 14:08:54 cd build_tools/
 1985  08/11/22 14:08:56 mkdir out
 1990  08/11/22 14:09:20 docker build --tag onlyoffice-document-editors-builder .
 1991  08/11/22 14:09:34 docker run -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder -d
 1992  08/11/22 14:09:45 docker run -d -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder

![image](https://user-images.githubusercontent.com/30200422/200543458-6e0eecc6-fa67-45c6-a00b-660399c016c4.png)

**Comment by ShockwaveNN** [comment]
This is strange, it's literally same command I've been using for years

Could you check it on another server? Maybe something wrong with this one, but not sure how it can be with docker

**Comment by ChiuJun** [comment]
@ShockwaveNN 

When I compile the source code in Ubuntu 16.04 VM using the command ``./automate.py server``，I had the same problem as  issue #527 .I checked the system monitor and found that the memory(or swap)  is not enough.When I extended the memory to 22GB, it succeeded.
I think at least  16GB RAM (or RAM+SWAP) is required

![IMG_3591](https://user-images.githubusercontent.com/42403968/202170049-11a79ced-cb88-41bf-9de1-968b384270f8.JPG)

But this is different from the [System requirements](https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx) section in the Docs,which one is correct？

**Comment by ShockwaveNN** [comment]
@ChiuJun I think it depends of host system, I'm usually build it on Ubuntu Server without GUI and I'm not 100% sure, but I think 2GB ram and 4GB SWAP may be enough

Maybe you got no swap at all? Because I think having some swap is more crucial, than a lot of RAM

**Comment by ChiuJun** [comment]
> @ChiuJun I think it depends of host system, I'm usually build it on Ubuntu Server without GUI and I'm not 100% sure, but I think 2GB ram and 4GB SWAP may be enough
> 
> Maybe you got no swap at all? Because I think having some swap is more crucial, than a lot of RAM

I agree, my SWAP is too small,this is the default for the Ubuntu installer. I adjusted the memory and SWAP in my Ubuntu VM and got the same error.
```bash
make[1]: Leaving directory '/home/vbox/server/core/ASCOfficeDocXFile2/Linux'
makefiles/build.makefile_linux_64:835: recipe for target 'sub--home-vbox-server-core-ASCOfficeDocXFile2-Linux-ASCOfficeDocxFile2Lib-pro-make_first-ordered' failed
make: *** [sub--home-vbox-server-core-ASCOfficeDocxFile2-Linux-ASCOfficeDocXFile2Lib-pro-make_first-ordered] Error 2
Error (make): 2
Error (./make.py): 1
```

![IMG_3616](https://user-images.githubusercontent.com/42403968/202423545-1e178101-b969-4740-8686-da025ebc2697.PNG)

There may be something wrong, but I have compiled successfully by extended the memory.
@ShockwaveNN Thanks!

**Comment by ShockwaveNN** [comment]
I think it may depend of host system and the version of compilator, I'll ask to change helpcenter entry to be somehow less precise, because there is a lot of factors and our product is really complicated

**Comment by ShockwaveNN** [comment]
I've created issue in our private repo for helpcenter to change wording

https://github.com/ONLYOFFICE/helpcenter/issues/41

I think I can close original issue, since OP is never returned
