### ISSUE TITLE
Build OnlyOffice ubuntu 16.04

### ISSUE THREAD

**Issue by yarodai** [ONLYOFFICE/build_tools#625]
os :ubuntu 16.04

Steps to reproduce the problem:
apt-get update
apt-get install -y python git
git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/tools/linux/
./automate.py server

![image](https://user-images.githubusercontent.com/12030364/218700662-9d819bed-86bd-412d-8305-fea37458592d.png)

**Comment by c0r3dump3d** [comment]
I have similar (not identical)  problems in Ubuntu 22.04, I tried before in Ubuntu 20.04 and I had problems with Nodejs and npm, in Ubuntu 22.04 I have problems with Qt (version 5.9.9) toolkit:

![imagen](https://user-images.githubusercontent.com/5602401/218780789-90886d1d-bb60-43ae-98f7-4863e6996d24.png)

Ubuntu 16.04 it's a bit old system (EOL April 2026). It would be recommended that this repository be updated to take into account more current versions of the operating system.

**Comment by yarodai** [comment]
> I have similar (not identical) problems in Ubuntu 22.04, I tried before in Ubuntu 20.04 and I had problems with Nodejs and npm, in Ubuntu 22.04 I have problems with Qt (version 5.9.9) toolkit:
> 
> ![imagen](https://user-images.githubusercontent.com/5602401/218780789-90886d1d-bb60-43ae-98f7-4863e6996d24.png)
> 
> Ubuntu 16.04 it's a bit old system (EOL April 2026). It would be recommended that this repository be updated to take into account more current versions of the operating system.

This is the version I use
npm: 6.14.18
nodejs: v10.24.1

**Comment by HeyVenus007** [comment]
os :ubuntu 16.04
the problem:
apt-get update
apt-get install -y python git
git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/tools/linux/
./automate.py server
![112233](https://user-images.githubusercontent.com/104475379/221343721-7632abd5-27de-4fb6-a50c-e9742312aefe.png)

**Comment by KernelDeimos** [comment]
Same build issue in docker image for ubuntu 22.04.

Solution was to explicitly add missing `#include <limits>` to the following file and run again:
```
tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/src/corelib/tools/qbytearraymatcher.h
```

I'm curious, how did this happen?

**Comment by igwyd** [comment]
Hello @yarodai, sorry for the late reply. We have released several new versions, and we checked build_tools. Could you please try compiling again?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
