### ISSUE TITLE
automate stop with an error:delete warning[file not exist]

### ISSUE THREAD

**Issue by HeyVenus007** [ONLYOFFICE/build_tools#630]
os :ubuntu 16.04
the problem:
apt-get update
apt-get install -y python git
git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/tools/linux/
./automate.py server
npm 9.5.1
node v16.15.1

![112233](https://user-images.githubusercontent.com/104475379/221348313-6231f2f6-3882-403c-a309-034240c84827.png)

**Comment by igwyd** [comment]
Hello @HeyVenus007, sorry for the late reply, buld_tools while compilation install the nodejs 14 and use this version, not 16.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
