### ISSUE TITLE
/home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/src/corelib/tools/qbytearray.cpp:42:

### ISSUE THREAD

**Issue by salansun** [ONLYOFFICE/build_tools#667]
`install dependencies...
install qt...
+ cd qtbase
+ /home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/configure -top-level -opensource -confirm-license -release -shared -accessibility -prefix ./../qt_build/Qt-5.9.9/gcc_64 -qt-zlib -qt-libpng -qt-libjpeg -qt-xcb -qt-pcre -no-sql-sqlite -no-qml-debug -gstreamer 1.0 -nomake examples -nomake tests -skip qtenginio -skip qtlocation -skip qtserialport -skip qtsensors -skip qtxmlpatterns -skip qt3d -skip qtwebview -skip qtwebengine
Creating qmake...
.In file included from /home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/src/corelib/tools/qbytearray.cpp:42:
/home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/src/corelib/tools/qbytearraymatcher.h: In static member function ‘static QStaticByteArrayMatcherBase::Skiptable QStaticByteArrayMatcherBase::generate(const char*, uint)’:
/home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/src/corelib/tools/qbytearraymatcher.h:103:38: error: ‘numeric_limits’ is not a member of ‘std’
  103 |         const auto uchar_max = (std::numeric_limits<uchar>::max)();
      |                                      ^~~~~~~~~~~~~~
/home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/src/corelib/tools/qbytearraymatcher.h:103:58: error: expected primary-expression before ‘>’ token
  103 |         const auto uchar_max = (std::numeric_limits<uchar>::max)();
      |                                                          ^
/home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/src/corelib/tools/qbytearraymatcher.h:103:61: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  103 |         const auto uchar_max = (std::numeric_limits<uchar>::max)();
      |                                                             ^~~
      |                                                             std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/include/QtCore/../../src/corelib/global/qglobal.h:109,
                 from /home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/include/QtCore/qglobal.h:1,
                 from /home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/include/QtCore/../../src/corelib/thread/qatomic.h:41,
                 from /home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/include/QtCore/qatomic.h:1,
                 from /home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/include/QtCore/../../src/corelib/tools/qrefcount.h:43,
                 from /home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/include/QtCore/qrefcount.h:1,
                 from /home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/src/corelib/tools/qbytearray.h:44,
                 from /home/ubuntu/onlyoffice/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/src/corelib/tools/qbytearray.cpp:41:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
gmake: *** [Makefile:304:`

**Comment by igwyd** [comment]
Hi @salansun, sorry for the late reply. Have you followed our guide and have you updated your server? We have released a new version, could you please try compiling again?

**Comment by chongxishen** [comment]
i add #include <limits>  in qbytearraymatcher.h, and it work.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
