### ISSUE TITLE
lost hb.h header file

### ISSUE THREAD

**Issue by cnscottluo** [ONLYOFFICE/build_tools#693]
**Describe your problem**:

use `./automate.py builder server` to build, this error occurs

![image](https://github.com/ONLYOFFICE/build_tools/assets/10561969/1d5d80a0-59b8-4295-bbcb-8a6c33e48f49)

**build_tools base repo version**:

master (merged 7.4)

**Operating system**:
ubuntu 20.0.4

**Comment by wangziyan** [comment]
I have the same issue!

**Comment by K0R0L** [comment]
Please check file
.../core/Common/3dParty/harfbuzz/harfbuzz/src/hb.h
It created by .../core/Common/3dParty/harfbuzz/make.py and called from build_tools.
You can remove .../core/Common/3dParty/harfbuzz/harfbuzz folder and re-run automate.py

**Comment by wangziyan** [comment]
I solved this error by manually executing the '.../core/Common/3dParty/harfbuzz/make.py' file.
