### ISSUE TITLE
Error  recipe for target 'sub--onlyoffice-core-DesktopEditor-doctrenderer-doctrenderer-pro-make_first-ordered' failed

### ISSUE THREAD

**Issue by jacky539027** [ONLYOFFICE/build_tools#694]
run  cmd ： “ ./automate.py server”  failed

error info

cc1plus: warning: unrecognized command line option '-Wno-register'
In file included from ./config.h:38:0,
                 from doctrenderer.cpp:43:
./../common/SystemUtils.h: At global scope:
./../common/SystemUtils.h:43:24: warning: 'NSSystemUtils::gc_EnvApplicationName' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvApplicationName = L"APPLICATION_NAME";
                        ^
./../common/SystemUtils.h:45:24: warning: 'NSSystemUtils::gc_EnvApplicationNameDefault' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvApplicationNameDefault = L"ONLYOFFICE";
                        ^
./../common/SystemUtils.h:49:24: warning: 'NSSystemUtils::gc_EnvCompanyName' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvCompanyName = L"COMPANY_NAME";
                        ^
./../common/SystemUtils.h:51:24: warning: 'NSSystemUtils::gc_EnvCompanyNameDefault' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvCompanyNameDefault = L"Ascensio System SIA Copyright (c) 2022";
                        ^
./../common/SystemUtils.h:55:24: warning: 'NSSystemUtils::gc_EnvMethodEncrypt' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvMethodEncrypt = L"METHOD_CRYPT";
                        ^
./../common/SystemUtils.h:56:24: warning: 'NSSystemUtils::gc_EnvMethodEncryptDefault' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvMethodEncryptDefault = L"Strong";
                        ^
./../common/SystemUtils.h:57:24: warning: 'NSSystemUtils::gc_EnvCreator' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvCreator = L"CREATOR";
                        ^
./../common/SystemUtils.h:58:24: warning: 'NSSystemUtils::gc_EnvCreated' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvCreated = L"CREATED";
                        ^
./../common/SystemUtils.h:59:24: warning: 'NSSystemUtils::gc_EnvLastModifiedBy' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvLastModifiedBy = L"LAST_MODIFIED_BY";
                        ^
./../common/SystemUtils.h:60:24: warning: 'NSSystemUtils::gc_EnvModified' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvModified = L"MODIFIED";
                        ^
./../common/SystemUtils.h:61:24: warning: 'NSSystemUtils::gc_EnvMemoryLimit' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvMemoryLimit = L"X2T_MEMORY_LIMIT";
                        ^
./../common/SystemUtils.h:62:24: warning: 'NSSystemUtils::gc_EnvMemoryLimitDefault' defined but not used [-Wunused-variable]
  static const wchar_t* gc_EnvMemoryLimitDefault = L"4GiB";
                        ^
cc1plus: warning: unrecognized command line option '-Wno-register'
make[1]: Leaving directory '/onlyoffice/core/DesktopEditor/doctrenderer'
makefiles/build.makefile_linux_64:568: recipe for target 'sub--onlyoffice-core-DesktopEditor-doctrenderer-doctrenderer-pro-make_first-ordered' failed
make: *** [sub--onlyoffice-core-DesktopEditor-doctrenderer-doctrenderer-pro-make_first-ordered] Error 2
Error (make): 2
Error (./make.py): 1

**Comment by lichao0223** [comment]
I have the same issue

**Comment by igwyd** [comment]
Hi @jacky539027, sorry for the late reply. What OS did you used? Have you followed our [guide](https://github.com/ONLYOFFICE/build_tools) and have you updated your server? We have released a new version, could you please try compiling again?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
