### ISSUE TITLE
Replace font document with garbled code

### ISSUE THREAD

**Issue by xiaohuochaia** [ONLYOFFICE/build_tools#713]
After compiling version 7.4.0 and replacing the Chinese font pack, there were very few incorrect numbers displayed in the document. The specific characters were: "time, fee, give", and the official Docker image was used instead. The replacement font also had the same problem,

**Comment by igwyd** [comment]
Hello @xiaohuochaia, sorry for the late reply. Could you describe your issue in more detail, what fonts have you removed, added, or used? Please provide the scenario.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
