### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by puqianglin** [ONLYOFFICE/build_tools#731]
Traceback (most recent call last):
  File "./make.py", line 70, in <module>
    make_common.make()
  File "scripts/core_common/make_common.py", line 38, in make
    boost.make()
AttributeError: 'module' object has no attribute 'make'
Error (./make.py): 1

python 2.7.12
ubuntu 16.04.7 LTS

**Comment by igwyd** [comment]
Hello @puqianglin, i checked right now compilation on the same stand ubuntu 16.04.7 LTS with python 2.7.12 and not get an error. Do you update server before compilation? This is a clean server? CPU and RAM? How command do you run compilation ```./automate.py```?

**Comment by puqianglin** [comment]
I first downloaded the Ubuntu image and compiled it using a virtual machine following Readme.MD steps；
RAM：4G
CPU：inter core i5

**Comment by igwyd** [comment]
I think there may be problems due to memory. I'm testing the compilation on 8GB RAM and 4 core CPU. Try running it again with 8GB RAM and 4-8 SWAP on a clean, updated server.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
