### ISSUE TITLE
Building a specific version of ONLYOFFICE (from tag)

### ISSUE THREAD

**Issue by mrtndwrd** [ONLYOFFICE/build_tools#74]
I'm trying to build for a specific version. I was hoping I could checkout the build_tools repo of a specific tag (in this case I tried `v5.5.1.84`) and run `build_tools/linux/automate.py` to build. However, the `get_branch_name` function then returns an empty string, because I'm not on a branch (I'm in a headless git repo, so `git symbolic-ref --short -q HEAD` does not work in that case).

Is there another way to achieve this? Or is this a bug? I can make a PR that does `git describe --tags` instead, if that's appreciated?

**Comment by ShockwaveNN** [comment]
> I was hoping I could checkout the build_tools repo of a specific tag (in this case I tried v5.5.1.84)

No, i think it will not work.

You can try run `python3 ./configure`
After that edit `./config` file to change variable `branch` to specific tag and run `automate.py`.

**Comment by mrtndwrd** [comment]
Thanks, I thought about that, but wouldn't `automate.py` overwrite the configuration?

**Comment by ShockwaveNN** [comment]
@mrtndwrd I'm not 100% sure, but I think it should not

**Comment by ShockwaveNN** [comment]
Fix is released on master
Problem should be fixed
