### ISSUE TITLE
compile error  OSError: [Errno 2] No such file or directory: 'v8'

### ISSUE THREAD

**Issue by sinbadabb** [ONLYOFFICE/build_tools#741]
win 10 8700K 16G ram  vm ws pro 17 ,new vm,cpu 1u 8C ,8G ram,80G HD, new ubuntu server 16.04.07 install from iso
after install ubuntu 16, run with python 2.7...
sudo apt update && sudo apt upgrade
sudo apt-get install openssh-server
sudo apt-get install -y python git
git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/tools/linux
./automate.py server

root@ubuntu:/home/sinbada/build_tools/tools/linux# ./automate.py server
---------------------------------------------
build branch: master
---------------------------------------------
---------------------------------------------
build modules: server
---------------------------------------------
[git] update: core
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: document-server-integration
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: sdkjs
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: document-templates
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: sdkjs-forms
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: core-fonts
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: server
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: dictionaries
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: onlyoffice.github.io
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[git] update: web-apps
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[fetch & build]: boost
[fetch & build]: cef
[fetch & build]: icu
[fetch & build]: openssl
/home/sinbada/build_tools/scripts/../../core/Common/3dParty/v8_89/depot_tools/vpython3: line 52: /home/sinbada/build_tools/scripts/../../core/Common/3dParty/v8_89/depot_tools/.cipd_bin/vpython3: No such file or directory
Directory not copied. Error: [Errno 2] No such file or directory: './v8/third_party'
Running depot tools as root is sad.
/home/sinbada/build_tools/scripts/../../core/Common/3dParty/v8_89/depot_tools/vpython3: line 52: /home/sinbada/build_tools/scripts/../../core/Common/3dParty/v8_89/depot_tools/.cipd_bin/vpython3: No such file or directory
Running depot tools as root is sad.
/home/sinbada/build_tools/scripts/../../core/Common/3dParty/v8_89/depot_tools/vpython3: line 52: /home/sinbada/build_tools/scripts/../../core/Common/3dParty/v8_89/depot_tools/.cipd_bin/vpython3: No such file or directory
Directory not copied. Error: [Errno 2] No such file or directory: './v8/third_party_new/ninja'
copy warning [file not exist]: v8/third_party/jinja2/tests.py
[replaceInFile] file not exist: v8/third_party/jinja2/tests.py
Traceback (most recent call last):
  File "./make.py", line 70, in <module>
    make_common.make()
  File "scripts/core_common/make_common.py", line 42, in make
  File "scripts/core_common/modules/v8.py", line 76, in make
  File "scripts/core_common/modules/v8_89.py", line 119, in make
OSError: [Errno 2] No such file or directory: 'v8'
Error (./make.py): 1

**Comment by sinbadabb** [comment]
run sudo ./automate.py server ,  error again

**Comment by sinbadabb** [comment]
[https://github.com/flutter/flutter/issues/92357](url)

**Comment by igwyd** [comment]
I checked the build on currently updated Ubuntu 16.04 and 20.04, with 4 core cpu, 8 gb ram, 8 gb swap, 80 gb ssd and didn't get any errors. What do you mean ```cpu 1u 8C``` ?

**Comment by sinbadabb** [comment]
in vm ,1 CPU 8Core.i had compiled it. the error reason is Chinese GFW.

**Comment by flyingShawn** [comment]
> thx .in vm ,1 CPU 8Core. i had compiled it. the error reason is Chinese Great FireWall

I have the same problem,help me!How to fix it?
我的vpn设置的，ubuntu上防火墙也关了，但是还是有问题，请问要怎么做。

**Comment by aLazyBear** [comment]
> > thx .in vm ,1 CPU 8Core. i had compiled it. the error reason is Chinese Great FireWall
> 
> I have the same problem,help me!How to fix it? 我的vpn设置的，ubuntu上防火墙也关了，但是还是有问题，请问要怎么做。

Can you resolve it?I also meet this error after set vpn
