### ISSUE TITLE
what is "Transport unknow" ?

### ISSUE THREAD

**Issue by ldinger** [ONLYOFFICE/build_tools#757]
after buils_tools 's working 
ver  7. 5  
websocket is working
docservice 's log print 
  [WARN] [localhost] [docId] [userId] nodeJS - io.connection_error code=0, message=Transport unknown

help !!!

**Comment by igwyd** [comment]
Hello @ldinger, describe in more detail scenario how are you check it? Which integration did you used afer complitely building documentserevr?

**Comment by ldinger** [comment]
Hello:
I use your official nodejs client demo program to create and open a docx document on the homepage and print "Transport unknown" in the background in the future.
I don't know what went wrong

**Comment by igwyd** [comment]
Looks like a test example configuration error. Do you have errors in the documentserver log?

**Comment by ldinger** [comment]
thanks
I think my problem has been solved
It was a configuration error in nginx that resulted in the loss of HTTP parameters for request forwarding

**Comment by umagmrit** [comment]
> thanks I think my problem has been solved It was a configuration error in nginx that resulted in the loss of HTTP parameters for request forwarding

@ldinger Could you please share what changes you made to the Nginx configuration to resolve this issue ?
