### ISSUE TITLE
Ubuntu16.04 Compile completed，the welcome page didn't show up

### ISSUE THREAD

**Issue by fowny** [ONLYOFFICE/build_tools#767]
**Steps to reproduce the problem**:
Compile:
```
apt-get update
apt-get install -y python git
git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/tools/linux
./automate.py server
```

Run:
```
git clone https://github.com/ONLYOFFICE-QA/onlyoffice-documentserver-run-compiled.git
DOCUMENT_SERVER_RESULTS="$HOME/build_tools/out"
docker build --tag documentserver Ubuntu16.04 
docker run -itd -p 80:80 -v${DOCUMENT_SERVER_RESULTS}:/out documentserver
```

local host shows below:
        ![image](https://github.com/ONLYOFFICE/build_tools/assets/103498127/a15a49b3-859f-43ad-966d-51c5e1a108c4)

**build_tools base repo version**:
```
v7.5.1
v7.5.0.136
```
**Operating system**:
`Ubuntu16.04`
**Compiler version**:
```
v7.5.1
v7.5.0.136
```

**Comment by fowny** [comment]
I tested with Debian11 :

> git clone --branch v7.5.0.136 https://github.com/ONLYOFFICE/build_tools.git  /root/build_tools
> cd /root/build_tools
> mkdir out
> docker build --tag onlyoffice-document-editors-builder .
> docker run -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder

and still got the same result

**Comment by yuanphoenix** [comment]
How do you fix it？I meet the same problem

**Comment by igwyd** [comment]
@yuanphoenix hello, the welcome page is missing from build_tools, it is added after and depending on the delivery.

**Comment by junaidbs** [comment]
not fixed
