### ISSUE TITLE
ERROR: The OpenGL functionality tests failed!

### ISSUE THREAD

**Issue by SkorokhodovVA** [ONLYOFFICE/build_tools#771]
Compiling the Docs Server on ubuntu 16.04 in both virtualbox and docker, an error occurs at the configure qt 5.9.9 stage

ERROR: Feature 'xcb' was enabled, but the pre-condition 'libs.xcb' failed.

ERROR: The OpenGL functionality tests failed!
You might need to modify the include and library search paths by editing QMAKE_INCDIR_OPENGL[_ES2],
QMAKE_LIBDIR_OPENGL[_ES2] and QMAKE_LIBS_OPENGL[_ES2] in the mkspec for your platform.

ERROR: Feature 'gstreamer_1_0' was enabled, but the pre-condition 'libs.gstreamer_1_0' failed.

Check config.log for details.
Error (./configure): 3

**Comment by igwyd** [comment]
Hello @SkorokhodovVA. The qt errors often are happening because server have not enough resources. Try to compile with 4cpu, 8ram, 8 swap, no less then 60GB ssd.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
