### ISSUE TITLE
How do I build the specified version?

### ISSUE THREAD

**Issue by yiwen9488** [ONLYOFFICE/build_tools#776]
The new version is buggy, I want to build the version of the previous document specified, what do I do here

**Comment by igwyd** [comment]
Hello @yiwen9488, what bugs do you mean? Describe in more detail please, this help us. As far as i know our hotfix 7.5.1 compiles without bugs. 
About your question: you can disable update - add ```update="0"``` in the ```.../build_tools/config```, swich to the desired version by tag or commit and run ```make.py```.

**Comment by yiwen9488** [comment]
Ok, got it. If there's a mistake, I've already reported it under the documentserver library

**Comment by yiwen9488** [comment]
@igwyd 
Hello,
> .../build_tools/config
I did not find the config file in this directory, git switching tag is a bit troublesome, is there an easier way

**Comment by igwyd** [comment]
This file ```build_tools/config``` creating if you run the compilation before. As i know we havent other way to compile old versions.

**Comment by yiwen9488** [comment]
> `build_tools/config`如果您之前运行编译，则会创建此文件。据我所知，我们没有其他方法来编译旧版本。
@igwyd 
Well, thank you for your help
I want to know what kind of environment is required for compiling web-apps separately. It takes too long to execute the command./automate.py server

**Comment by igwyd** [comment]
Unfortunately we still haven't detailed documentation, you can follow the update this issue https://github.com/ONLYOFFICE/build_tools/issues/751
