### ISSUE TITLE
Using build_ Tools are built and executed locally/ Automate.py encountered an exception. Please help me solve it, thank you

### ISSUE THREAD

**Issue by 9527-lang** [ONLYOFFICE/build_tools#779]
Execution/ Automate.py or/ Deps.py has been experiencing this issue consistently. This caused me to keep compiling unsuccessfully. I tried to install nodejs and npm successfully, but this problem also occurred. I am a new Ubuntu 14 LTS system
![Snipaste_2023-12-27_18-14-25](https://github.com/ONLYOFFICE/build_tools/assets/40056768/7f7aaafb-e322-4226-9a19-610241d35cab)

Please reply as soon as possible. Thank you. @igwyd

**Comment by igwyd** [comment]
Hello @9527-lang, sorry for the late reply. We don't test compilation on ubuntu less then 16.04, i guess there may be problems. Can you try compile on the Ubuntu 16.04 - 20.04? I recommend doing this on the server with not less then 4 cpu 8 RAM and outside Great firewall of china.

**Comment by zhangft7478191** [comment]
我也遇到一样的问题，你需要换成server版本就可以了。 猜测desktop版本的问题。

镜像建议选择：

> http://mirrors.aliyun.com/ubuntu-releases/16.04/ubuntu-16.04.7-server-amd64.iso

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
