### ISSUE TITLE
SVG-icon file contents erased by 'svnmin' task while building DocumentServer on Linux OS

### ISSUE THREAD

**Issue by rupalijaiswal** [ONLYOFFICE/build_tools#780]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.5.0

### Expected Behavior

All icons in document server must be displayed properly. For: shapes dropdown, charts drop down icons.

<img width="280" alt="Capture2" src="https://github.com/ONLYOFFICE/DocumentServer/assets/48027779/e0253214-c951-496c-9f4e-26d5b78b0028">

### Actual Behavior

When DocumentServer 7.5.0 is build on Linux OS, icon files in 'web-apps/apps/**/resources/img/..' folders are minified and placed into 'web-apps/deploy/..' folder.
We have noticed that some svg file contents are erased while minified.
Due to this the shapes, charts, etc icons are not rendered properly. Refer attached image:

<img width="278" alt="Capture" src="https://github.com/ONLYOFFICE/DocumentServer/assets/48027779/1cf2648f-9618-41eb-b70f-e82779076bb2">

**Comment by Maaayank** [comment]
Hi @Rita-Bubnova  any update on this, I am facing the same issue on my setup as well.

OS : Ubuntu linux
Version: 7.5.0

**Comment by igwyd** [comment]
Hello @rupalijaiswal, @Maaayank , we do not support old versions. Now actual version is 7.5.1. I checked compilation today on the ubuntu 20.04 and i have the icons. Could you try compile current version 7.5.1? If this happens again on the current version, please provide more details on the steps to reproduce?

Icons after my compilation process:
![image](https://github.com/ONLYOFFICE/build_tools/assets/67538082/58f68e33-f7c1-4f7f-89df-d64393675482)

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
