### ISSUE TITLE
compile error fatal: Couldn't find remote ref remotes/branch-heads/8.9

### ISSUE THREAD

**Issue by HZL3151904214** [ONLYOFFICE/build_tools#781]
cpu 2C ,4G ram,60G HD, new ubuntu server 16.04.07 install from iso
after install ubuntu 16, run with python 2.7

build_tools base repo version:
7.5.1

git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/tools/linux
./automate.py server

Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
[fetch & build]: boost
[fetch & build]: cef
[fetch & build]: icu
[fetch & build]: openssl
Cloning into 'depot_tools'...
remote: Sending approximately 53.15 MiB ...
remote: Total 57183 (delta 37906), reused 57183 (delta 37906)
Receiving objects: 100% (57183/57183), 53.15 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (37906/37906), done.
Checking connectivity... done.
Running: gclient root
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Your current directory appears to already contain, or be part of, 
a checkout. "fetch" is used only to get new checkouts. Use 
"gclient sync" to update existing checkouts.

Fetch also does not yet deal with partial checkouts, so if fetch
failed, delete the checkout and start over (crbug.com/230691).
Directory not copied
Running depot tools as root is sad.

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /usr/hzl/core/Common/3dParty/v8_89/_gclient_v8_fdbd0674' in '/usr/hzl/core/Common/3dParty/v8_89'
Cloning into '/usr/hzl/core/Common/3dParty/v8_89/_gclient_v8_fdbd0674'...
remote: Sending approximately 1.09 GiB ...
remote: Counting objects: 7456, done
Receiving objects:  11% (118673/1067020), 49.30 MiB | 1.79 MiB/s   
remote: Total 1067020 (delta 864533), reused 1067020 (delta 864533)
Receiving objects: 100% (1067020/1067020), 1.08 GiB | 1.70 MiB/s, done.
Resolving deltas:  81% (707160/864533)   
Resolving deltas: 100% (864533/864533), done.
Checking connectivity... done.
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin" "remotes/branch-heads/8.9" "--no-tags"' in /usr/hzl/core/Common/3dParty/v8_89/v8 failed; will retry after a short nap...

[0:14:10] Still working on:
[0:14:10]   v8
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin" "remotes/branch-heads/8.9" "--no-tags"' in /usr/hzl/core/Common/3dParty/v8_89/v8 failed; will retry after a short nap...

[0:14:20] Still working on:
[0:14:20]   v8

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /usr/hzl/core/Common/3dParty/v8_89/_gclient_v8_l7n7umxw' in '/usr/hzl/core/Common/3dParty/v8_89'
Cloning into '/usr/hzl/core/Common/3dParty/v8_89/_gclient_v8_l7n7umxw'...

[0:14:30] Still working on:

Receiving objects:  91% (970989/1067020), 1.06 GiB | 1.80 MiB/s   
[0:25:40] Still working on:
[0:25:40]   v8
Receiving objects:  99% (1056350/1067020), 1.08 GiB | 1.80 MiB/s   
[0:25:50] Still working on:
[0:25:50]   v8
remote: Total 1067020 (delta 864533), reused 1067020 (delta 864533)
Receiving objects: 100% (1067020/1067020), 1.08 GiB | 1.80 MiB/s, done.
Resolving deltas:  54% (470661/864533)   
[0:26:00] Still working on:
[0:26:00]   v8
Resolving deltas:  65% (567013/864533)   
[0:26:10] Still working on:
[0:26:10]   v8
Resolving deltas:  75% (648444/864533)   
[0:26:20] Still working on:
[0:26:20]   v8
Resolving deltas:  83% (719339/864533)   
[0:26:30] Still working on:
[0:26:30]   v8
Resolving deltas:  90% (781184/864533)   
[0:26:40] Still working on:
[0:26:40]   v8
Resolving deltas:  95% (824861/864533)   
[0:26:50] Still working on:
[0:26:50]   v8
Resolving deltas: 100% (864533/864533), done.
Checking connectivity... done.

[0:27:00] Still working on:
[0:27:00]   v8

[0:27:10] Still working on:
[0:27:10]   v8

[0:27:20] Still working on:
[0:27:20]   v8

[0:27:30] Still working on:
[0:27:30]   v8

[0:27:40] Still working on:
[0:27:40]   v8

[0:27:50] Still working on:
[0:27:50]   v8

[0:28:00] Still working on:
[0:28:00]   v8

[0:28:10] Still working on:
[0:28:10]   v8
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin" "remotes/branch-heads/8.9" "--no-tags"' in /usr/hzl/core/Common/3dParty/v8_89/v8 failed; will retry after a short nap...

[0:28:20] Still working on:
[0:28:20]   v8
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin" "remotes/branch-heads/8.9" "--no-tags"' in /usr/hzl/core/Common/3dParty/v8_89/v8 failed; will retry after a short nap...

[0:28:29] Still working on:
[0:28:29]   v8
Syncing projects: 100% ( 1/ 1) v8
v8 (ERROR)

[0:00:00] Started.
[0:00:00] 
fatal: Couldn't find remote ref remotes/branch-heads/8.9
[0:14:19] fatal: Couldn't find remote ref remotes/branch-heads/8.9
[0:14:23] _____ Conflicting directory found in /usr/hzl/core/Common/3dParty/v8_89/v8. Moving to /usr/hzl/core/Common/3dParty/v8_89/_bad_scm/v8xo6_8v4h.
[0:14:23] 
[0:28:10] fatal: Couldn't find remote ref remotes/branch-heads/8.9
[0:28:24] fatal: Couldn't find remote ref remotes/branch-heads/8.9

Error: Command 'git -c core.deltaBaseCacheLimit=2g fetch origin remotes/branch-heads/8.9 --no-tags' returned non-zero exit status 128 in /usr/hzl/core/Common/3dParty/v8_89/v8

Warnings:
Conflicting directory /usr/hzl/core/Common/3dParty/v8_89/v8 moved to /usr/hzl/core/Common/3dParty/v8_89/_bad_scm/v8xo6_8v4h.

Running depot tools as root is sad.
Directory not copied
copy warning [file not exist]: v8/third_party/jinja2/tests.py
[replaceInFile] file not exist: v8/third_party/jinja2/tests.py
gn gen out.gn/linux_64 --args="v8_static_library=true is_component_build=false v8_monolithic=true v8_use_external_startup_data=false use_custom_libcxx=false treat_warnings_as_errors=false target_cpu=\"x64\" v8_target_cpu=\"x64\" is_debug=false is_clang=true use_sysroot=false"
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.
Error (gn): 1
Error (./make.py): 1
Error (./make.py): 1[0:26:30]: command not found

**Comment by Aima09** [comment]
Hi @HZL3151904214 ,I have the same issue with you,could you tell me how did you solve this problem?
