### ISSUE TITLE
Docker build failed and stopped at grunt-google-closure-compiler

### ISSUE THREAD

**Issue by shooding** [ONLYOFFICE/build_tools#790]
Follow instructions at [https://github.com/ONLYOFFICE/build_tools/tree/master/develop](https://github.com/ONLYOFFICE/build_tools/tree/master/develop)

Pulling latest baseImage FROM onlyoffice/documentserver:latest (checksum = 8.0) 24 days ago
Build on M1 with --platform=linux/amd64 to build the image "documentserver-develop" successfully
Then use the 

...

run with sdkjs and web-apps (with --platform=linux/amd64) because my final deployment is on linux/amd64

`docker run --platform=linux/amd64 -i -t -p 80:80 --restart=always -e ALLOW_PRIVATE_IP_ADDRESS=true -v $(pwd)/sdkjs:/var/www/onlyoffice/documentserver/sdkjs -v $(pwd)/web-apps:/var/www/onlyoffice/documentserver/web-apps documentserver-develop`

```
/usr/bin/yes: standard output: Broken pipe
...
Running "closure-compiler:js" (closure-compiler) task
>> grunt-google-closure-compiler: Compilation errors occurred
Warning: Compilation error Use --force to continue.
```

**Comment by igwyd** [comment]
Hello @shooding  I guess the issue is the same as https://github.com/ONLYOFFICE/build_tools/issues/407, compilation on Mac OS, we still havn't guide.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
