### ISSUE TITLE
How do you compile individual modules separately

### ISSUE THREAD

**Issue by yiwen9488** [ONLYOFFICE/build_tools#795]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Many times only need to compile the server sdk web-apps, according to the script alone out of the compilation will always be less things or errors! Is there a better way?

**Comment by BaseOrange** [comment]
So? Is there any solution to this problem?

**Comment by igwyd** [comment]
@BaseOrange we have this guide https://github.com/ONLYOFFICE/build_tools/tree/master/develop is this what you mean?

**Comment by BaseOrange** [comment]
Hello, igwyd.
I'm glad to receive your reply. 
Actually, I want to ask, is there any way to just package web-apps or sdkjs?

**Comment by igwyd** [comment]
I know we have packages for different OS https://github.com/ONLYOFFICE/document-server-package, but I don't understand what you mean a package for separaed modules. Could you describe your case and I'll try to find out if we have this.
