### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by lugeluge** [ONLYOFFICE/build_tools#8]
could you give us a readme about how to use the script like which variable we need to change

**Comment by ShockwaveNN** [comment]
@lugeluge I working on it now, you can monitor progress at https://github.com/ONLYOFFICE/build_tools/pull/7

**Comment by ShockwaveNN** [comment]
It is not ready, but I'm working on it - see https://github.com/ONLYOFFICE/build_tools/pull/7

**Comment by ShockwaveNN** [comment]
Now we got an instruction, please see README.md
