### ISSUE TITLE
Using build_ Tools are built and executed locally/ Automate.py encountered an exception. Please help me solve it, thank you

### ISSUE THREAD

**Issue by aLazyBear** [ONLYOFFICE/build_tools#803]
ubuntu version : 16.04 
sudo ./automate.py server，Error file can not be found, please help me to see what is the reason。thx
![image](https://github.com/ONLYOFFICE/build_tools/assets/11979936/e43b6788-e9a2-4f22-967d-614ead6d6c5f)

**Comment by adriangibanelbtactic** [comment]
I recommend to copy and paste your error messages as text, not as an image.
That's the expected behavior when reporting an issue.

**Comment by igwyd** [comment]
Hello @aLazyBear, sorry for the late reply. Provide please the information about hadware of your server and steps to reproduse.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
