### ISSUE TITLE
URI is malformed cannot open the document

### ISSUE THREAD

**Issue by warnerbryce** [ONLYOFFICE/build_tools#81]
Greatings everyone,

I have a working version of own compiled OnlyOffice/DocumentServer 
i can go on https://office.domain.fr/welcome or /healthcheck 
I use the Nextcloud OnlyOffice App and it's configured that way : 
Server address of OnlyOffice : https://office.domain.fr/
Internal address of OnlyOffice : http://localhost:8000/
Nextcloud server address : https://cloud.domain.fr/

When i open a doc on Nextcloud, I have the OnlyOffice frame that is running, and an endless Loading for the doc. 

Here is what i get on the log : 
```
[2020-04-21T11:07:21.063] [ERROR] nodeJS - changesError: docId = 3578365501 Error: SyntaxError: The URI is malformed. Script: https://office.domain.fr/sdkjs/word/sdk-all-min.js Line: 336:0 userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0 platform: Linux x86_64 isLoadFullApi: true isDocumentLoadComplete: false StackTrace: dg/<@https://office.domain.fr/sdkjs/word/sdk-all-min.js:336:54
dg@https://office.domain.fr/sdkjs/word/sdk-all-min.js:336:158
Cb@https://office.domain.fr/sdkjs/word/sdk-all-min.js:324:370
f.AscCommon.Vff@https://office.domain.fr/sdkjs/word/sdk-all-min.js:399:422
Pa.prototype.Ogd@https://office.domain.fr/sdkjs/word/sdk-all-min.js:672:170
Pa.prototype.PSd/this.al.UMa@https://office.domain.fr/sdkjs/word/sdk-all-min.js:682:483
Pa.prototype.o0e@https://office.domain.fr/sdkjs/word/sdk-all-min.js:114:130
Pa.prototype.se/this.cl.UMa@https://office.domain.fr/sdkjs/word/sdk-all-min.js:107:170
Xa.prototype.ALe@https://office.domain.fr/sdkjs/word/sdk-all-min.js:127:18
Xa.prototype.nNe@https://office.domain.fr/sdkjs/word/sdk-all-min.js:140:204
Xa.prototype.ygd/Ia.onmessage@https://office.domain.fr/sdkjs/word/sdk-all-min.js:138:500
[5]</r.prototype.dispatchEvent@https://office.domain.fr/web-apps/vendor/sockjs/sockjs.min.js:2:2901
[14]</</r.prototype._transportMessage/<@https://office.domain.fr/web-apps/vendor/sockjs/sockjs.min.js:2:12862
[14]</</r.prototype._transportMessage@https://office.domain.fr/web-apps/vendor/sockjs/sockjs.min.js:2:12840
[3]</r.prototype.emit@https://office.domain.fr/web-apps/vendor/sockjs/sockjs.min.js:2:1767
r/this.ws.onmessage@https://office.domain.fr/web-apps/vendor/sockjs/sockjs.min.js:3:4926


```

And here is the Nginx log : 
```
`2020/04/21 11:07:20 [notice] 6342#6342: *1614 "^\/OfficeWeb(\/apps\/.*)$" does not match "/doc/3578365501/c/346/yvgjow0s/websocket", client: 192.168.10.254, server: office.domain.fr, request: "GET /doc/3578365501/c/346/yvgjow0s/websocket HTTP/1.1", host: "office.domain.fr"
`

```

It's really odd because if i type in my browser thoses url with web-apps ... .js i can see those files.

**Comment by ShockwaveNN** [comment]
I've moved this issue to build_tools repo

**Comment by warnerbryce** [comment]
Update on this issue : 
I have build again with this version 5.5.1 
Now i can't get /welcome to display. i get CANNOT GET /welcome.
I have /healthcheck and /index.html that are working.
I didn't use the nginx reverse proxy because it is worse, 
I use http://XXX.XXX.XXX.XXX:8000/healthcheck for exemple.

So i have no error logs into the DocService process...

**Comment by warnerbryce** [comment]
Update : 
I've compiled again a working 5.5.1 OnlyOffice document server but : 
I canot get http://IPv4ofServer:8000/welcome working ... i get CANNOT GET /welcome
Only healthcheck return true and index.html return : Server is functioning normally. Version: 5.5.1. Build: 0
I have no error nor debug logs on docservice while doing this manipulation...
I put redis on port mode with port 6379 and localhost 
When i try to connect via Nextcloud admin OnlyOffice panel from a server outside of the OnlyOffice server i get this :  
```
2020/04/22 11:50:04 [notice] 8712#8712: *499 "^\/OfficeWeb(\/apps\/.*)$" does not match "/healthcheck", client: EXTERNAL_IP, server: office.domain.fr, request: "GET /healthcheck HTTP/1.1", host: "office.domain.fr"
2020/04/22 11:50:04 [info] 8712#8712: *499 client EXTERNAL_IP closed keepalive connection
2020/04/22 11:50:04 [notice] 8712#8712: *501 "^\/OfficeWeb(\/apps\/.*)$" does not match "/coauthoring/CommandService.ashx", client: EXTERNAL_IP, server: office.domain.fr, request: "POST /coauthoring/CommandService.ashx HTTP/1.1", host: "office.domain.fr"
2020/04/22 11:50:04 [info] 8712#8712: *501 client EXTERNAL_IP closed keepalive connection
2020/04/22 11:50:04 [notice] 8712#8712: *503 "^\/OfficeWeb(\/apps\/.*)$" does not match "/ConvertService.ashx", client: EXTERNAL_IP, server: office.domain.fr, request: "POST /ConvertService.ashx HTTP/1.1", host: "office.domain.fr"
2020/04/22 11:50:05 [info] 8712#8712: *503 client EXTERNAL_IP closed keepalive connection

```

Does the Nginx conf file isn't faulty or need a tweaking ?

**Comment by ShockwaveNN** [comment]
> I canot get http://IPv4ofServer:8000/welcome working ... i get CANNOT GET /welcome
> Only healthcheck return true and index.html return : Server is functioning normally

Yes, this is correct behavior, since welcome page is not included in this build

Other issues I need to check, I never tryed to connect compiled version to nextcloud, only to our own nodejs integration example

**Comment by warnerbryce** [comment]
@ShockwaveNN this problem is present in my old version from 21th of January. 
I don't know if it is related with the Nginx reverse proxy file or another file that breaks the return URL.
I can't see where this bad URL is formatted so i can't diagnose more.
I cross finger that will be an easy fix because i put so much hope on it.

**Comment by ShockwaveNN** [comment]
If this error not new and you have pretty complicated setup - I think you should try same config with deb version of DocumentServer (or Docker) and see if this problem actual for all version of DocumentServer or just compiled from source

**Comment by warnerbryce** [comment]
@ShockwaveNN this isn’t new but only for the DocumentServer Compiled version. 
The Docker version always work, the old as the newer one. But the docker version don’t have the same nginx proxy file. 
I tried this file on the DS compiled but same error.

**Comment by ShockwaveNN** [comment]
>  But the docker version don’t have the same nginx proxy file.

To be clear - you mean config file from https://github.com/ONLYOFFICE/build_tools#installing-and-configuring-nginx this step?

**Comment by warnerbryce** [comment]
@ShockwaveNN yes it’s the file i use with the compiled version. I just add the « server_name office.domain.fr; » line and then lunch certbot for ssl connection

**Comment by ShockwaveNN** [comment]
@warnerbryce could you try to temporary disable ssl and check that error is same?

**Comment by warnerbryce** [comment]
@ShockwaveNN I can't 
mixed content is forbidden.
Nextcloud don't want to connect to http OnlyOffice server nor ownsigned SSL certs.

The SSL works fine because i can access to the same pages with https://office.domain.fr/ and http://192.168.XXX.XXX//. And if i attack from outside my LAN https://office.domain.fr/ it behaves the same.

**Comment by ShockwaveNN** [comment]
> mixed content is forbidden.
yeah, I hope you temproarly disable ssl on nextcloud side also

But ok

We'll try to connect with our instance of nextcloud as soon as compilation is finished, but without SSL and see if got any errors

**Comment by warnerbryce** [comment]
@ShockwaveNN It behaves the same with FULL HTTP. 
The URL is wrongly created with a duplicate http://office.domain.fr, office.domain.fr/......

**Comment by ShockwaveNN** [comment]
@warnerbryce Same error if use ip address instead of domain with Full HTTP?

**Comment by warnerbryce** [comment]
> @warnerbryce Same error if use ip address instead of domain with Full HTTP?

Yeah it gave http://XXX.XXX.XXX.XXX, XXX.XXX.XXX.XXX/.....

**Comment by ShockwaveNN** [comment]
So, I just connected my compiled instance to nextcloud without ssl on both parts and my similar logs seems like this:

```
[2020-04-22T14:13:52.140] [DEBUG] nodeJS - Start commandFromServer: docId = undefined c = version
[2020-04-22T14:13:52.140] [DEBUG] nodeJS - End commandFromServer: docId = undefined {"error":0,"version":"5.5.1.0"}
[2020-04-22T14:13:52.171] [DEBUG] nodeJS - Start convert request docId = conv_check_1132276900_docx
[2020-04-22T14:13:52.179] [DEBUG] nodeJS - Start Task(id=conv_check_1132276900_docx)
[2020-04-22T14:13:52.426] [DEBUG] nodeJS - downloadFile complete filesize=6994 (id=conv_check_1132276900_docx)
[2020-04-22T14:13:52.471] [DEBUG] nodeJS - stdout (id=conv_check_1132276900_docx):
[2020-04-22T14:13:52.471] [DEBUG] nodeJS - stderr (id=conv_check_1132276900_docx):
[2020-04-22T14:13:52.471] [DEBUG] nodeJS - ExitCode (code=0;signal=null;error:0;id=conv_check_1132276900_docx)
[2020-04-22T14:13:52.475] [DEBUG] nodeJS - processUploadToStorage complete(id=conv_check_1132276900_docx)
[2020-04-22T14:13:52.475] [DEBUG] nodeJS - output (data={"cmd":{"withAuthorization":true,"c":"conv","id":"conv_check_1132276900_docx","format":"docx","url":"http://nct-enterprise.tk/cloud/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.yOmL859Xo-1kC7rK-So2dS94B4dtF_eWslsbUlQhFuA","title":"check_1132276900.docx","outputformat":65,"outputpath":"output.docx","codepage":46,"delimiter":4,"embeddedfonts":false,"status_info":0,"nobase64":true}};id=conv_check_1132276900_docx)
[2020-04-22T14:13:52.476] [DEBUG] nodeJS - postProcess (id=conv_check_1132276900_docx)
[2020-04-22T14:13:52.477] [DEBUG] nodeJS - deleteFolderRecursive (id=conv_check_1132276900_docx)
[2020-04-22T14:13:52.481] [DEBUG] nodeJS - Start receiveTask: docId = conv_check_1132276900_docx {"cmd":{"withAuthorization":true,"c":"conv","id":"conv_check_1132276900_docx","format":"docx","url":"http://nct-enterprise.tk/cloud/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.yOmL859Xo-1kC7rK-So2dS94B4dtF_eWslsbUlQhFuA","title":"check_1132276900.docx","outputformat":65,"outputpath":"output.docx","codepage":46,"delimiter":4,"embeddedfonts":false,"status_info":0,"nobase64":true}}
[2020-04-22T14:13:52.484] [DEBUG] nodeJS - End receiveTask: docId = conv_check_1132276900_docx
[2020-04-22T14:13:53.185] [DEBUG] nodeJS - End convert request end true url http://ip.ip.ip.ip/cache/files/conv_check_1132276900_docx/output.docx/check_1132276900.docx?md5=04kJ1YaR_ILVXOWEq_reyQ&expires=1587565734&disposition=attachment&filename=check_1132276900.docx status 0 docId = conv_check_1132276900_docx
```

Last line looks correct

So, can you show your nginx current config file?

**Comment by warnerbryce** [comment]
Here is my onlyoffice.conf file : 
```
map $http_host $this_host {
  "" $host;
  default $http_host;
}
map $http_x_forwarded_proto $the_scheme {
  default $http_x_forwarded_proto;
  "" $scheme;
}
map $http_x_forwarded_host $the_host {
  default $http_x_forwarded_host;
  "" $this_host;
}
map $http_upgrade $proxy_connection {
  default upgrade;
  "" close;
}
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Forwarded-Host $the_host;
proxy_set_header X-Forwarded-Proto $the_scheme;
server {
  error_log /var/log/nginx/only.error.log debug;
  server_tokens off;
  server_name office.domain.fr;
  rewrite ^\/OfficeWeb(\/apps\/.*)$ /web-apps$1 redirect;
  location / {
    proxy_pass http://localhost:8000;
    proxy_http_version 1.1;
  }
  location /spellchecker/ {
    proxy_pass http://localhost:8080/;
    proxy_http_version 1.1;
  }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/office.domain.fr/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/office.domain.fr/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = office.domain.fr) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


}

```

I am using Nextcloud 18.0.3 and i tested on a 17.0.5 too

**Comment by ShockwaveNN** [comment]
I see there is only difference with ssl settings

Could you try to use exact same as I use from https://github.com/ONLYOFFICE/build_tools#installing-and-configuring-nginx?

In meantime we've update our nextcloud instance to v18 (currently we test in with 17) and see if got any similar errors

**Comment by warnerbryce** [comment]
> Could you try to use exact same as I use from https://github.com/ONLYOFFICE/build_tools#installing-and-configuring-nginx?
> 
That what i use when i test in full HTTP mode, this is exactly the same, just with one line for server_name

**Comment by ShockwaveNN** [comment]
@warnerbryce Ok, while we are in process of upgrade of our nextcloud instance - could you contact me via shockwavenn@gmail.com

We'll try to connect you nextcloud with mine compiled DocumentServer

**Comment by ShockwaveNN** [comment]
Ok, seems this resolved problem (in email), runining compiled version in container
https://github.com/onlyoffice-testing-robot/documentserver-from-source-build/tree/feature/use-build-tools

But I still don't understand what is the problem.

Last question - that host system did you use to run not-containered DocumentServer?

**Comment by warnerbryce** [comment]
This host never fully had a working compiled version of OnlyOffice. 
I always used the docker pull command with onlyoffice/DocumentServer 
I started to compile the code just some days ago. 

I think there is : 
A- something to do with the nginx template that didn’t match
B- something when loading the commands that is lacking, and that the docked script solved.

**Comment by ShockwaveNN** [comment]
> This host never fully had a working compiled version of OnlyOffice.

Yeah, but which host? maybe I will be able to repdocue, my hosts was Ubuntu 14.04 for compilation (Since it's only compile on 14.04) and Ubuntu 18.04 for running comiple version.

**Comment by warnerbryce** [comment]
I had a ubuntu 14.04.6 that never finished the process but it was the automate.py server bug. 

I use the docker 14.04.4 for compiling and it works. 
For fire up processes it is a ubuntu 18.04

**Comment by ShockwaveNN** [comment]
@warnerbryce Ok, in such case I'm out of ideas. But glad to hear that it's working for you now
