### ISSUE TITLE
build the v8_89 error

### ISSUE THREAD

**Issue by lingchentc** [ONLYOFFICE/build_tools#812]
I executed au.py server to start the build，When building the v8 engine, the following error occurred:
fatal: Couldn't find remote ref remotes/branch-heads/8.9

My operating system is Ubuntu 16.

Please hlep me,thanks!

**Comment by igwyd** [comment]
Hello @lingchentc, we know about it and already fixed. Its will bw fixed in the next major release.
Duplicate of #807

**Comment by lingchentc** [comment]
> Hello @lingchentc, we know about it and already fixed. Its will bw fixed in the next major release. Duplicate of #807

thanks!

**Comment by Aima09** [comment]
@lingchentc 嘿,兄弟,你这个问题是怎么解决的?没看到他们在哪个commit里修复了啊

**Comment by lingchentc** [comment]
> @lingchentc 嘿,兄弟,你这个问题是怎么解决的?没看到他们在哪个commit里修复了啊

@Aima09 我暂时没看出来，他们关联的另一个issue https://github.com/ONLYOFFICE/build_tools/issues/807 里，看修改是添加了python3，没有看到修复v8编译的部分
