### ISSUE TITLE
"Cannot find module './editorDataRedis' " 

### ISSUE THREAD

**Issue by PlatonaBoy** [ONLYOFFICE/build_tools#873]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.1.1

### Expected Behavior

start process successfully when using the program which is builded from open source by ourself.

### Actual Behavior

pkg/prelude/bootstrap.js:1872
 throw error:
"Cannot find module './editorDataRedis' "
equire stack:

/snapshot/server/DocService/sources/DocsCoServer.js
/snapshot/server/DocService/sources/canvasservice.js
/snapshot/server/DocService/sources/wopiClient.js
/snapshot/server/FileConverter/sources/converter.js
/snapshot/server/FileConverter/sources/convertermaster.js

### Reproduction Steps

clone open source
Compile the program using build_tools
edit conf with redis & run process

### Additional information

No response

**Comment by PlatonaBoy** [comment]
.https://github.com/ONLYOFFICE/DocumentServer/issues/2647
This issue was closed due no response.
No cause or solution given

**Comment by igwyd** [comment]
Hello @PlatonaBoy, [this issue ](https://github.com/ONLYOFFICE/DocumentServer/issues/2647) was closed due no response.
About your issue, [build_tools](https://github.com/ONLYOFFICE/build_tools/) was developed for compile community version of the documentsever. The redis module is not used in the documentserver community version, so it is not here.

**Comment by PlatonaBoy** [comment]
How to get the redis module

**Comment by igwyd** [comment]
To do this, please contact the sales department sales@onlyoffice.com

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
