### ISSUE TITLE
"After compilation, the api.js file was not generated, and there is an api.js.tpl file instead, which prevents the system from functioning."

### ISSUE THREAD

**Issue by PlatonaBoy** [ONLYOFFICE/build_tools#880]
Description: After compiling the project, the expected api.js file was not created. Instead, an api.js.tpl file was generated, which is preventing the system from functioning correctly.

Steps to reproduce the problem:

Clone the repository and ensure you have the latest master of build_tools.
Run the compilation process.
Check the output directory for the presence of the api.js file.
build_tools base repo version:
Operating system: ubnutu20.4

Compiler version: 8.2.0

**Comment by yuanphoenix** [comment]
same question

**Comment by yuanphoenix** [comment]
But you can rename it to api.js
It works ok

**Comment by igwyd** [comment]
Hello, thank you for the report, i confirm this is bug, issue #71385

**Comment by vulgarcoder** [comment]
I just modified the deploy_server.py file by changing 'base.move_file' to 'base.copy_file' on line 117, and now the build works fine.

**Comment by yuanphoenix** [comment]
> I just modified the deploy_server.py file by changing 'base.move_file' to 'base.copy_file' on line 117, and now the build works fine.

It is a good solution!

**Comment by zsy1314** [comment]
> But you can rename it to api.js It works ok

It works for me too

**Comment by yuanphoenix** [comment]
> > But you can rename it to api.js It works ok
> 
> It works for me too

Do you have another question like miss the Icons？

**Comment by zsy1314** [comment]
> > > But you can rename it to api.js It works ok
> > 
> > 
> > It works for me too
> 
> Do you have another question like miss the Icons？

I don't know which icons you are referring to, the icons on the top toolbar are not missing. But when I used version 7.2.1, I encountered the situation where the icons on the top toolbar disappeared after compiling. At that time, I manually copied the icons in the source file to the corresponding path.

```
# word
\web-apps\apps\documenteditor\main\resources\img
\build_tools\out\linux_64\onlyoffice\documentserver\web-apps\apps\documenteditor\main\resources\img
# ppt
\web-apps\apps\presentationeditor\main\resources\img
\build_tools\out\linux_64\onlyoffice\documentserver\web-apps\apps\presentationeditor\main\resources\img
# excel
\web-apps\apps\spreadsheeteditor\main\resources\img
\build_tools\out\linux_64\onlyoffice\documentserver\web-apps\apps\spreadsheeteditor\main\resources\img
# common1
\web-apps\apps\common\main\resources\img\controls
\build_tools\out\linux_64\onlyoffice\documentserver\web-apps\apps\common\main\resources\img\controls
# common2
\web-apps\apps\common\main\resources\img\toolbar
\build_tools\out\linux_64\onlyoffice\documentserver\web-apps\apps\common\main\resources\img\toolbar
# Restart DocumentServer
```
I don't know if it's still valid now.

**Comment by yuanphoenix** [comment]
> > > > But you can rename it to api.js It works ok
> > > 
> > > 
> > > It works for me too
> > 
> > 
> > Do you have another question like miss the Icons？
> 
> I don't know which icons you are referring to, the icons on the top toolbar are not missing. But when I used version 7.2.1, I encountered the situation where the icons on the top toolbar disappeared after compiling. At that time, I manually copied the icons in the source file to the corresponding path.
> 
> ```
> # word
> \web-apps\apps\documenteditor\main\resources\img
> \build_tools\out\linux_64\onlyoffice\documentserver\web-apps\apps\documenteditor\main\resources\img
> # ppt
> \web-apps\apps\presentationeditor\main\resources\img
> \build_tools\out\linux_64\onlyoffice\documentserver\web-apps\apps\presentationeditor\main\resources\img
> # excel
> \web-apps\apps\spreadsheeteditor\main\resources\img
> \build_tools\out\linux_64\onlyoffice\documentserver\web-apps\apps\spreadsheeteditor\main\resources\img
> # common1
> \web-apps\apps\common\main\resources\img\controls
> \build_tools\out\linux_64\onlyoffice\documentserver\web-apps\apps\common\main\resources\img\controls
> # common2
> \web-apps\apps\common\main\resources\img\toolbar
> \build_tools\out\linux_64\onlyoffice\documentserver\web-apps\apps\common\main\resources\img\toolbar
> # Restart DocumentServer
> ```
> 
> I don't know if it's still valid now.

Okay，Thank you.

**Comment by Rita-Bubnova** [comment]
Version 8.2.2 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
