### ISSUE TITLE
Do not have the icon

### ISSUE THREAD

**Issue by yuanphoenix** [ONLYOFFICE/build_tools#882]
# Describe your problem:
Comlile success ,And i run it in Java Spring example. but i do not have icon.I think it is abnormal.
![image](https://github.com/user-attachments/assets/dcbb198c-cdeb-42d0-a441-d54419492e8f)

the master branch.Anything wrong?

**Comment by igwyd** [comment]
Hello @yuanphoenix, please try with nodejs example https://api.onlyoffice.com/docs/docs-api/get-started/language-specific-examples/nodejs-example/. I'll ask collegue to check Java Spring example.

**Comment by yuanphoenix** [comment]
> Hello @yuanphoenix, please try with nodejs example https://api.onlyoffice.com/docs/docs-api/get-started/language-specific-examples/nodejs-example/. I'll ask collegue to check Java Spring example.

I user the official docker image.It can show the icon,so I think it is not the java's problem.Maybe I meet some compile question on this project.Do you know where are these icon from?

**Comment by igwyd** [comment]
As i know they should be downloaded from this repository https://github.com/ONLYOFFICE/web-apps/tree/8b6e1dbf6ff6025632ae3c4750db02949ad458ea/apps/documenteditor/main/resources/img/toolbar for documenteditor for example

**Comment by yuanphoenix** [comment]
I compile it again.It works well now.

![image](https://github.com/user-attachments/assets/a7d177cc-c176-4afe-ae6e-5f8d3e4fc708)
