### ISSUE TITLE
Can higher versions of NodeJS be used

### ISSUE THREAD

**Issue by Shorakie** [ONLYOFFICE/build_tools#883]
Is NodeJs 16 the only version that can be used to build or higher versions can be used as well such as NodeJs18.

as the installation of nodejs script suggests the 16 version (Gallium) is deprecated and Nodejs 18 is suggested which is in maintenance.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
