### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by stereo720712** [ONLYOFFICE/build_tools#91]
i try to set CXXFLAGS but still fail
the error message:

> 
../../src/objects-body-descriptors.h:101:22: note:   template argument deduction/substitution failed:
../../src/objects-body-descriptors.h:102:20: note:   candidate expects 2 arguments, 1 provided
     IterateBody(obj);
                    ^
cc1plus: all warnings being treated as errors
[4/1402] CXX obj/src/inspector/inspector/v8-debugger.o
ninja: build stopped: subcommand failed.
Error (ninja): 1
Error (./make.py): 1

> 
can anyone tell me how to do? thanks

**Comment by ShockwaveNN** [comment]
Which os and gcc are you using?

**Comment by dany1** [comment]
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

the same problem

**Comment by ShockwaveNN** [comment]
As it mention in instruction current solution works only on Ubuntu 14.04 (or use provided Dockerfile)
https://github.com/ONLYOFFICE/build_tools#how-to-use---linux

And since this error happens on v8 stage - you can google those error and found a lot of post about similar v8 compilation falures

**Comment by stereo720712** [comment]
i use ubuntu 18.04 lts,

**Comment by stereo720712** [comment]
> As it mention in instruction current solution works only on Ubuntu 14.04 (or use provided Dockerfile)
> https://github.com/ONLYOFFICE/build_tools#how-to-use---linux
> 
> And since this error happens on v8 stage - you can google those error and found a lot of post about similar v8 compilation falures

thanks  i have tried a lot , but  all failed .

**Comment by stereo720712** [comment]
the version i used
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by stereo720712** [comment]
i try in ubuntu14.04
and error in v8.make()
i try google that , but not sure what 's the problem 
Can I manual make to build v8 and put it in some where ?
ninja: Entering directory `out.gn/linux_64'
[1360/1400] LINK ./mksnapshot
FAILED: mksnapshot 
#toolchain.ninja
python "../../build/toolchain/gcc_link_wrapper.py" --output="./mksnapshot" -- g++ -pie -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -m64 -pthread -Werror -Wl,-rpath-link=. -Wl,--disable-new-dtags -Wl,-O1 -Wl,--gc-sections -o "./mksnapshot" -Wl,--start-group @"./mksnapshot.rsp"  -Wl,--end-group   -ldl -lrt 
o, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
obj/libv8_libbase.a(platform-linux.o):platform-linux.cc:function v8::base::OS::GetSharedLibraryAddresses(): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)'
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)'
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
obj/libv8_libbase.a(stack_trace_posix.o):stack_trace_posix.cc:function v8::base::debug::(anonymous namespace)::DemangleSymbols(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const'
obj/libv8_libbase.a(stack_trace_posix.o):stack_trace_posix.cc:function v8::base::debug::(anonymous namespace)::DemangleSymbols(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const'
obj/libv8_libbase.a(stack_trace_posix.o):stack_trace_posix.cc:function v8::base::debug::(anonymous namespace)::DemangleSymbols(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)'
obj/libv8_libbase.a(stack_trace_posix.o):stack_trace_posix.cc:function v8::base::debug::(anonymous namespace)::DemangleSymbols(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
obj/libv8_libbase.a(stack_trace_posix.o):stack_trace_posix.cc:function v8::base::debug::(anonymous namespace)::DemangleSymbols(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
obj/libv8_libbase.a(stack_trace_posix.o):stack_trace_posix.cc:function v8::base::debug::(anonymous namespace)::DemangleSymbols(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
obj/libv8_libbase.a(stack_trace_posix.o):stack_trace_posix.cc:function v8::base::debug::(anonymous namespace)::DemangleSymbols(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Error (ninja): 1
Error (./make.py): 1
apple@ubuntu:/media/psf/Home/docuument_server/build_tools/tools/linux$

**Comment by stereo720712** [comment]
i try for different problem 
can anyone help ?

ninja: Entering directory `out.gn/linux_64'
[1/41] LINK ./d8
FAILED: d8 
python "../../build/toolchain/gcc_link_wrapper.py" --output="./d8" -- g++ -pie -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -m64 -pthread -Werror -Wl,-rpath-link=. -Wl,--disable-new-dtags -Wl,-O1 -Wl,--gc-sections -o "./d8" -Wl,--start-group @"./d8.rsp"  -Wl,--end-group   -ldl -lrt 
obj/libv8_libbase.a(platform-linux.o):platform-linux.cc:function v8::base::OS::GetSharedLibraryAddresses(): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
obj/libv8_libbase.a(platform-linux.o):platform-linux.cc:function v8::base::OS::GetSharedLibraryAddresses(): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)'
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)'
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
obj/libv8_libplatform.a(trace-config.o):trace-config.cc:function v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled(char const*) const: error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const'
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const'
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const'
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)'
obj/libv8_libplatform.a(trace-writer.o):trace-writer.cc:function v8::platform::tracing::JSONTraceWriter::AppendArgValue(unsigned char, v8::platform::tracing::TraceObject::ArgValue): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
obj/src/inspector/libinspector.a(search-util.o):search-util.cc:function v8_inspector::(anonymous namespace)::findMagicComment(v8_inspector::String16 const&, v8_inspector::String16 const&, bool): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
obj/src/inspector/libinspector.a(search-util.o):search-util.cc:function v8_inspector::searchInTextByLinesImpl(v8_inspector::V8InspectorSession*, v8_inspector::String16 const&, v8_inspector::String16 const&, bool, bool): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
obj/src/inspector/libinspector.a(search-util.o):search-util.cc:function v8_inspector::searchInTextByLinesImpl(v8_inspector::V8InspectorSession*, v8_inspector::String16 const&, v8_inspector::String16 const&, bool, bool): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
obj/src/inspector/libinspector.a(v8-console-message.o):v8-console-message.cc:function v8_inspector::V8ConsoleMessage::createForConsoleAPI(v8::Local<v8::Context>, int, int, v8_inspector::V8InspectorImpl*, double, v8_inspector::ConsoleAPIType, std::vector<v8::Local<v8::Value>, std::allocator<v8::Local<v8::Value> > > const&, std::unique_ptr<v8_inspector::V8StackTraceImpl, std::default_delete<v8_inspector::V8StackTraceImpl> >): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
obj/libv8_libbase.a(stack_trace_posix.o):stack_trace_posix.cc:function v8::base::debug::(anonymous namespace)::DemangleSymbols(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const'
obj/libv8_libbase.a(stack_trace_posix.o):stack_trace_posix.cc:function v8::base::debug::(anonymous namespace)::DemangleSymbols(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const'
obj/libv8_libbase.a(stack_trace_posix.o):stack_trace_posix.cc:function v8::base::debug::(anonymous namespace)::DemangleSymbols(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)'
obj/libv8_libbase.a(stack_trace_posix.o):stack_trace_posix.cc:function v8::base::debug::(anonymous namespace)::DemangleSymbols(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Error (ninja): 1
Error (./make.py): 1

**Comment by ShockwaveNN** [comment]
@stereo720712 Try gcc 4.8.4 on Ubuntu 14.04

Or use provided Dockerfile, it's just three steps

**Comment by stereo720712** [comment]
> @stereo720712 Try gcc 4.8.4 on Ubuntu 14.04
> 
> Or use provided Dockerfile, it's just three steps

thanks i will try

**Comment by stereo720712** [comment]
sorry but i success make v8 ,and get another problem about qt
can anyone help to know what's the problem ?
thanks
 [1065/1491] CXX obj/test/unittests/unittests/task-queue-unittest.o
[1491/1491] STAMP obj/gn_all.stamp
------------------------------------------
BUILD_PLATFORM: linux_64
------------------------------------------
make: makefiles/build.makefile_linux_64: No such file or directory
make: *** No rule to make target `makefiles/build.makefile_linux_64'.  Stop.
make: makefiles/build.makefile_linux_64: No such file or directory
make: *** No rule to make target `makefiles/build.makefile_linux_64'.  Stop.
/media/psf/Home/docuument_server/build_tools/tools/linux/qt_build/Qt-5.9.9/gcc_64/bin/qmake: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /media/psf/Home/docuument_server/build_tools/tools/linux/qt_build/Qt-5.9.9/gcc_64/bin/qmake)
Error (/media/psf/Home/docuument_server/build_tools/tools/linux/qt_build/Qt-5.9.9/gcc_64/bin/qmake): 1
Error (./make.py): 1

**Comment by ShockwaveNN** [comment]
I'm not sure, but that error may be because you builded qt using newer gcc, and starting build of our project with gcc 4.8.4
Try to cleanup everythin and start anew

If problem still exists - please provide step by step instruciton (or Dockerfile better) how to reproduce it

**Comment by stereo720712** [comment]
> I'm not sure, but that error may be because you builded qt using newer gcc, and starting build of our project with gcc 4.8.4
> Try to cleanup everythin and start anew
> 
> If problem still exists - please provide step by step instruciton (or Dockerfile better) how to reproduce it
thanks  your reply
my gcc version is 4.8.4 ,right

**Comment by ShockwaveNN** [comment]
Just compiled project without any error using Dockerfile

So I need you to provide your Dockerfile how to reproduce error

**Comment by stereo720712** [comment]
thanks @ShockwaveNN  teaching,
I try use docker building ,
failed here ,
May you know what the problem ?
thanks.
------------------------------------------
BUILD_PLATFORM: linux_64
------------------------------------------

install dependencies...
install qt...
---------------------------------------------
build branch: master
---------------------------------------------
---------------------------------------------
build modules: desktop builder server
---------------------------------------------
Error (./make.py): 1

**Comment by ShockwaveNN** [comment]
@stereo720712 I need more output

**Comment by ShockwaveNN** [comment]
Seems this issue is resolved, since same user created error about steps after these
