### ISSUE TITLE
Source code of editors_helper.exe file

### ISSUE THREAD

**Issue by linuxqtcppexamples** [ONLYOFFICE/build_tools#92]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
source code not find for editors_helper.exe 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
without editors_helper.exe DesktopEditor.exe will not show word/xls/pdf.

**What is the expected behavior?**
 DesktopEditor.exe is showing an empty screen.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Windows 10, Qt 5.9.8 MSVC 2015 64 bit.

**Comment by ShockwaveNN** [comment]
As we mention earlier - until we have correct instruction about how to build our product on Windows - I don't think we can resolve this issue

**Comment by linuxqtcppexamples** [comment]
Hi,
i observed editors_helper.exe in 5.5.1 released build.
I am unable to find which source in github will generate editors_helper.exe file.
This not related to build instructions, i am looking source path of editors_helper.exe

**Comment by ShockwaveNN** [comment]
> This not related to build instructions

Until there is no instruction I cannot help you either.
Maybe @K0R0L has some info, but I'm not sure

**Comment by K0R0L** [comment]
https://github.com/ONLYOFFICE/desktop-sdk/blob/master/ChromiumBasedEditors/lib/ascdocumentscore_helper.pro
